### ISSUE TITLE
Add option to download the GPX file of a Workout

### ISSUE THREAD

**Issue by albertodiazsaez** [SamR1/FitTrackee#115]
While on the Workout screen, a button or link to download the original GPX file of that Workout.

**Comment by SamR1** [comment]
Hi

For now, uploaded gpx files are not modified (just renamed).
Is it to retrieve a file more easily?

**Comment by albertodiazsaez** [comment]
Yes! My phone automatically uploads .gpx files to FitTrackee, and sometimes I want to grab them to map in OSM, or to analyze them in an external software, and instead of going to the folder backup, I would love to be able to download them from the webpage.

**Comment by SamR1** [comment]
ok, thanks for your answer.
