### ISSUE TITLE
Better UI for Speed and Elevation buttons in the graph of the Workout screen

### ISSUE THREAD

**Issue by albertodiazsaez** [SamR1/FitTrackee#116]
With the new UI in 0.5.0, I think is not clear that the legend of the graph (Speed/Elevation), are also buttons to hide/show the data, I only knew it because in 0.4.9 was possible, and at first I thought the functionality was removed.

![imagen](https://user-images.githubusercontent.com/40151953/142411747-678e6bdd-65e0-4662-8483-5fc035660e16.png)

![imagen](https://user-images.githubusercontent.com/40151953/142411762-f16055c1-3757-4bfa-8011-738ae1de803d.png)

**Comment by SamR1** [comment]
Hi,

Thanks for you feedback.
The chart library is different from v0.5, the default legend may be not clear especially for users of previous versions.
