### ISSUE TITLE
Add followers/following and visibility levels

### ISSUE THREAD

**Issue by SamR1** [SamR1/FitTrackee#125]
- visibility levels applied to workouts and geolocation data 
  - `private`: only workout owner can access data
  - `followers_only`: only followers of workout owner can access data
  - `public`: everyone can access data

- data visibility 

A user can set visibility for workout data and geolocation data separately.

|                  |                          | user<sup>1</sup>                  | follower                                            | owner              |
|------------------|--------------------------|-----------------------------------|-----------------------------------------------------|--------------------|
| Profile          | Header (username, stats) | :white_check_mark:                | :white_check_mark:                                  | :white_check_mark: |
|                  | User info                | :white_check_mark:                | :white_check_mark:                                  | :white_check_mark: |
|                  | Preferences              | :x:                               | :x:                                                 | :white_check_mark: |
|                  | Sport preferences        | :x:                               | :x:                                                 | :white_check_mark: |
| Workout          | Title / Data             | :ballot_box_with_check: if public | :ballot_box_with_check: if public or followers only | :white_check_mark: |
|                  | Records                  | :ballot_box_with_check: if public | :ballot_box_with_check: if public or followers only | :white_check_mark: |
|                  | Description              | :ballot_box_with_check: if public | :ballot_box_with_check: if public or followers only | :white_check_mark: |
|                  | Notes                    | :x:                               | :x:                                                 | :white_check_mark: |
| Geolocation Data | Map            | :ballot_box_with_check: if public | :ballot_box_with_check: if public or followers only | :white_check_mark: |
|                  | Analysis  (charts)         | :ballot_box_with_check: if public | :ballot_box_with_check: if public or followers only | :white_check_mark: |

- By default, all data are private.

---

1.  authenticated and unauthenticated users

**Comment by Firesphere** [comment]
Oh, can't wait for this to be finished! Would love to be able to publicly share certain parts of my rides!

**Comment by SamR1** [comment]
released in v0.9.0b1
