### ISSUE TITLE
parse_email_url() can't validate a legitimate EMAIL_URI such as "smtp://localhost:25"

### ISSUE THREAD

**Issue by vincentxavier** [SamR1/FitTrackee#127]
"smtp://localhost:25" is a valid, as of `urllib3.util.parse_url` and `parsed_url.auth` is `None`, so `.split(':')`, wont work.

**Comment by rwc0888** [comment]
> "smtp://localhost:25" is a valid, as of `urllib3.util.parse_url` and `parsed_url.auth` is `None`, so `.split(':')`, wont work.

I was stuck on this issue for a long time until I discovered [this](https://samr1.github.io/FitTrackee/installation.html#emails) in the documentation.  It seems you need to use something like `smtp://username:password@smtp.example.com:25`.

**Comment by SamR1** [comment]
Hi,

Sorry for the delay.

Yes, the valid format for **FitTrackee** is `smtp://username:password@host:port`.
But I will add support for email URL without authentication.
