### ISSUE TITLE
Is it possible to add own sports?

### ISSUE THREAD

**Issue by markusjdev** [SamR1/FitTrackee#139]
Hey @devs,

I like your software so far!
I want to know if it's possible to create a own sport (category, just like walking, hiking etc.)... it would be cool.

Thank you in advance.

MJ

**Comment by SamR1** [comment]
Hi,

It's not possible for now.  
What sport would you like to add?

**Comment by markusjdev** [comment]
Thanks for your quick response

Something like rally or racing (with cars/motorcycles/...).
Is it possible through the database?

**Comment by SamR1** [comment]
Sports are stored in the database, but icons and translations are client-side (Vue part).
