### ISSUE TITLE
Getting in touch regarding a possible security issue

### ISSUE THREAD

**Issue by DanielSiersleben** [SamR1/FitTrackee#148]
Hey there!

I recently stumbled across this app and possibly found a security issue I'd like to report.
However, I couldn't find any contact information or instruction to responsibly disclose the issue.
That's why opened the issue here to ask for any possible way to get in touch with you or if it's fine for you to mention my concerns here/start a pull request?

looking forward to hearing from you!

**Comment by SamR1** [comment]
Hi @DanielSiersleben,

thanks for the information, you can send me a message on matrix : @samr1:matrix.org.
