### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [SamR1/FitTrackee#158]
Hey there!

I belong to an open source security research community, and a member (@porcupineyhairs) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by SamR1** [comment]
Hi,

Thanks! I added  a [`SECURITY.md`](https://github.com/SamR1/FitTrackee/blob/master/SECURITY.md) file.

**Comment by JamieSlome** [comment]
@SamR1 - thanks for your response 👍 

We will get an e-mail sent over shortly. In the meantime, you can view the report directly here:
https://huntr.dev/bounties/b13a9ee0-a0bc-4548-93c0-a9c0a305ea9a/

It is private and only accessible to you.

**Comment by JamieSlome** [comment]
Just sent over the e-mail 📧
