### ISSUE TITLE
How are you using alembic for a new migration?

### ISSUE THREAD

**Issue by Fmstrat** [SamR1/FitTrackee#163]
Sorry if this shouldn't be here, I'm not sure where discussion should take place.

```
fmstrat@ubuntuDesktop:~/Documents/Repos/FitTrackee/fittrackee/migrations$ alembic revision -m "add ascent record"
  FAILED: No 'script_location' key found in configuration.
```
How should I be adding a new migration?

**Comment by Fmstrat** [comment]
I have another PR ready to go: https://github.com/SamR1/FitTrackee/compare/master...Fmstrat:elevation_record?expand=1, but need to add the migration. It's basic, just a:

```
ALTER TYPE record_types ADD VALUE 'HA';
```

**Comment by Fmstrat** [comment]
Sorry, one more question. Do you have a specific downgrade process you would like to use? Since the values aren't part of a normalized table and are an ENUM, there is no way to remove a value without creating a new ENUM and updating the tables to reference it. I could have the downgrade:
- Leave the new ENUM value
- Convert the tables ENUMs to VARCHARs, DROP the ENUM, make a new one, then convert back (would change order of columns)
- Convert the column to a varchar, then normalize the record_types into a `record_types` table with a constraint on the column in `user_records`.

Personally, I like number 3 as it eliminates any future issues with ENUMs.

**Comment by Fmstrat** [comment]
NOTE: Option 1 is still "safe" as the extra enum value isn't going to cause a problem on failure I wouldn't think. Option 1 is what's in the branch now.

**Comment by SamR1** [comment]
Hi,

I prefer the second option, for instance:

```python
def downgrade():
    op.execute("ALTER TYPE record_types RENAME TO record_types_old")
    op.execute("CREATE TYPE record_types AS ENUM('AS', 'FD', 'LD', 'MS')")
    op.execute(
        """
        ALTER TABLE records ALTER COLUMN record_type TYPE record_types 
        USING record_type::text::record_types
    """
    )
    op.execute("DROP TYPE record_types_old")
```

FYI, I initiated [contributing guidelines](https://github.com/SamR1/FitTrackee/blob/dev/CONTRIBUTING.md), with some instructions (including migrations).
