### ISSUE TITLE
cannot send email with TLS

### ISSUE THREAD

**Issue by PipeItToDevNull** [SamR1/FitTrackee#178]
I love the app so far, but I am trying to get email working with Office365. It seems that my URL

`smtp://noreply@dev0.sh:<pass>@smtp.office365.com:587/?tls=True` does not work. When I curl this I get a DNS resolution error because it is resolving the domain as `dev0.sh:<pass>@smtp.office365.com`. 

Could this DNS resolution error also be occurring in the app because I am an idiot and don't understand the example URL of `username:password`? Can I not use @ or do I need to encode that character?

**Comment by PipeItToDevNull** [comment]
Encoding `@` to `%40` allowed curl to work, so I will try this in my .env tonight

**Comment by PipeItToDevNull** [comment]
That did not resolve the issue. For whatever reason no attempt is made to login at all the 365

**Comment by SamR1** [comment]
Hi,

Thanks for your feedback. 
The `EMAIL_URL` looks OK, but there is a bug when sending email with TLS :/ (I'll fix it).
But the issue may persist with Office365, depending on [server configuration](https://answers.microsoft.com/en-us/msoffice/forum/all/535-573-authentication-unsuccessful/cd915151-ae89-4505-8ad3-29680554e710).

**Comment by SamR1** [comment]
Hi,

Emails are used to activate account, update email and reset password.
As workaround, a new CLI is available in the [latest release](https://github.com/SamR1/FitTrackee/releases/tag/v0.6.5) to manage user account.
So if you are running a single-user instance, you can now disable email sending.
