### ISSUE TITLE
Create user via CLI to remove all email requirements

### ISSUE THREAD

**Issue by PipeItToDevNull** [SamR1/FitTrackee#182]
Emails are used to activate account, update email and reset password.
As workaround, a new CLI is available in the [latest release](https://github.com/SamR1/FitTrackee/releases/tag/v0.6.5) to manage user account.
So if you are running a single-user instance, you can now disable email sending.

_Originally posted by @SamR1 in https://github.com/SamR1/FitTrackee/issues/178#issuecomment-1107861307_

---

I love this solution, for single user instances (or just a couple users) being able to make a user via CLI would remove the mailhog (and redis I think) requirements in the docker stack.

I do not believe it is currently possible to create a user outside of the email based registration process

**Comment by PipeItToDevNull** [comment]
Strike this, registration creates the user and then you can use CLI to activate and change the pass

**Comment by SamR1** [comment]
Hi,

> I love this solution, for single user instances (or just a couple users) being able to make a user via CLI would remove the mailhog (and redis I think) requirements in the docker stack.

Mailhog is an email testing tool, used in development. The docker files present in this repo are just for evaluation/development.
I updated docker files present in [another repository](https://github.com/SamR1/docker-fittrackee) to make Redis optional.
 
> I do not believe it is currently possible to create a user outside of the email based registration process

Yes, for now, the CLI only allows user account update. I will add more commands in next versions.
