### ISSUE TITLE
Map snippets are not displayed in dashboard

### ISSUE THREAD

**Issue by escuco** [SamR1/FitTrackee#189]
Hello!

On my setup the maps from the "Latest Workouts" on the dashboard are not displayed:

![snap1](https://user-images.githubusercontent.com/1647405/174570089-bca090aa-09a1-4b6c-9bab-63892c1c729c.JPG)

When I click on an workout, the map is shown correctly:
![snap2](https://user-images.githubusercontent.com/1647405/174570304-700b9484-3ba7-4dbf-8805-7eb9d047db71.JPG)

Until now I didn't changed the default map settings in `.env`, because the map per workout is fine:
```
# Workouts
# export TILE_SERVER_URL=
# export MAP_ATTRIBUTION=
# export DEFAULT_STATICMAP=False
# export WEATHER_API_KEY=
```

Is there anything I have to do to show up the maps in the dashboard?

**Comment by SamR1** [comment]
Hi,

It seems the image is not generated by `staticmap`, since it's still possible to display the map.
A .png file associated to the .gpx file should exist in workouts folder.

Are there any errors in the logs when adding a gpx?

**Comment by escuco** [comment]
Hello,

when adding a gpx there are no new error messages in the log.

But everytime I open the dashboard, it throws out one error for every missing png file:
```
2022/06/22 09:08:40 - fittrackee - ERROR - 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2022/06/22 09:08:40 - fittrackee - ERROR - 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2022/06/22 09:08:40 - fittrackee - ERROR - 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2022/06/22 09:08:40 - fittrackee - ERROR - 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2022/06/22 09:08:40 - fittrackee - ERROR - 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

I found two workouts folders. One in the FitTrackee main folder (/fittrackee/workouts/) with only an empty subfolder "1" in it.

And another workouts folder in /fittrackee/fittrackee/uploads/uploads/workouts/1/ with all uploaded gpx files and the corresponding static png maps files in it.

Do you have an idea what's going wrong here?

**Comment by SamR1** [comment]
Thanks for your answer.

My first guess was wrong.  
The error in logs indicates that FitTrackee can not open the map file. I reproduced the same kind of error in logs by manually renaming the .png file in workouts folder (I will update the error message in this case to be more relevant).  

Since FitTrackee can open gpx files, I don't think it's a permissions issue.  
One explanation could be that there is a mismatch between map filename stored in database and .png filename, but FitTrackee normally stores the path used to generate the map image.

**Comment by escuco** [comment]
Thank you!

That's the output from the second workouts directory ( /fittrackee/fittrackee/uploads/uploads/workouts/1/):
```
fittrackee) [fittrack@libra 1]$ ls -lisa
total 2424
1083825801   4 drwxrwxr-x. 2 fittrack fittrack   4096 Jun 22 09:08 .
 539065474   0 drwxrwxr-x. 3 fittrack fittrack     15 Jun 15 12:33 ..
1083825820  72 -rw-rw-r--. 1 fittrack fittrack  71407 Jun 15 12:33 2022-03-29 16:39:29.095000+02:00_Running_9kt422o1.png
1611054072 268 -rw-rw-r--. 1 fittrack fittrack 273623 Jun 22 09:08 2022-03-29 16:39:29.095000+02:00_Running_a6vc4whn.gpx
1079988530  72 -rw-rw-r--. 1 fittrack fittrack  71260 Jun 22 09:08 2022-03-29 16:39:29.095000+02:00_Running_opxmy3o8.png
1083825815 268 -rw-rw-r--. 1 fittrack fittrack 273623 Jun 15 12:33 2022-03-29 16:39:29.095000+02:00_Running_zyhngwa9.gpx
1611227461 220 -rw-rw-r--. 1 fittrack fittrack 223053 Jun 15 12:33 2022-04-25 16:29:40.541000+02:00_Running_87v5il1o.gpx
1083825809  76 -rw-rw-r--. 1 fittrack fittrack  77410 Jun 15 12:33 2022-04-25 16:29:40.541000+02:00_Running_vgf4itep.png
   5852234 144 -rw-rw-r--. 1 fittrack fittrack 144523 Jun 15 12:34 2022-05-02 16:05:09.325000+02:00_Running_1nk3jshz.gpx
1083825822  72 -rw-rw-r--. 1 fittrack fittrack  71550 Jun 15 12:34 2022-05-02 16:05:09.325000+02:00_Running_5guxklhm.png
1611227468 136 -rw-rw-r--. 1 fittrack fittrack 135189 Jun 15 12:33 2022-05-11 16:05:49.924000+02:00_Running_ou5c3wd9.gpx
1083825806  72 -rw-rw-r--. 1 fittrack fittrack  72871 Jun 15 12:33 2022-05-11 16:05:49.924000+02:00_Running__ysmj71c.png
 537749200 896 -rw-rw-r--. 1 fittrack fittrack 914231 Jun 19 18:47 2022-06-18 09:07:04+00:00_Cycling (Transport)_bpqcyql6.gpx
1075161827 124 -rw-rw-r--. 1 fittrack fittrack 125499 Jun 19 18:47 2022-06-18 09:07:04+00:00_Cycling (Transport)_tzbgizsa.png
```

So the permissions from the .png files are the same than the .gpx files.

With map file you mean the static generated .png file?
And do you perhaps know, why there is a second, empty workouts directory in /fittrackee/workouts/1/ ?

**Comment by SamR1** [comment]
I don't know if it's related, but I think I'll change the file naming to avoid some characters in file path.

**Comment by SamR1** [comment]
The [version just released](https://github.com/SamR1/FitTrackee/releases/tag/v0.6.8) contains some fixes, file naming change and updated dependencies.  
If the issue is file path related, this release may be able to fix it.

**Comment by escuco** [comment]
Thank you very much! 
I'll check the file paths in the database tomorrow and upgrade my installation.

**Comment by escuco** [comment]
Hello!
These are the database entries from the workouts table:

```
 id |                                  gpx                                  |                                  map
----+-----------------------------------------------------------------------+-----------------------------------------------------------------------
  1 | workouts/1/2022-04-25 16:29:40.541000+02:00_Running_87v5il1o.gpx      | workouts/1/2022-04-25 16:29:40.541000+02:00_Running_vgf4itep.png
  2 | workouts/1/2022-03-29 16:39:29.095000+02:00_Running_zyhngwa9.gpx      | workouts/1/2022-03-29 16:39:29.095000+02:00_Running_9kt422o1.png
  3 | workouts/1/2022-05-11 16:05:49.924000+02:00_Running_ou5c3wd9.gpx      | workouts/1/2022-05-11 16:05:49.924000+02:00_Running__ysmj71c.png
  4 | workouts/1/2022-05-02 16:05:09.325000+02:00_Running_1nk3jshz.gpx      | workouts/1/2022-05-02 16:05:09.325000+02:00_Running_5guxklhm.png
  5 | workouts/1/2022-06-18 09:07:04+00:00_Cycling (Transport)_bpqcyql6.gpx | workouts/1/2022-06-18 09:07:04+00:00_Cycling (Transport)_tzbgizsa.png
  6 | workouts/1/2022-03-29 16:39:29.095000+02:00_Running_a6vc4whn.gpx      | workouts/1/2022-03-29 16:39:29.095000+02:00_Running_opxmy3o8.png
(6 rows)
```
I can't see any mismatches with the .png filenames.

Will upgrade later and see, how it works then.

**Comment by escuco** [comment]
What I've done now:

- upgraded to FitTrackee v0.6.8
- deleted all old workouts
- uploaded one new workout

It's the same behavior, the map on the dashboard is not shown, the osm map in the workout view is fine.

Output from /home/fittrack/fittrackee/fittrackee/uploads/workouts/1/ : 
```
1083825809  72 -rw-rw-r--. 1 fittrack fittrack  71301 Jun 23 09:35 2022-03-29_14-39-29_5_7dqnr8e6.png
 537628705 268 -rw-rw-r--. 1 fittrack fittrack 273623 Jun 23 09:35 2022-03-29_14-39-29_5_te9sf5bv.gpx
```

Output from the database:
```
 id |                      gpx                      |                      map                      |              map_id
----+-----------------------------------------------+-----------------------------------------------+----------------------------------
  7 | workouts/1/2022-03-29_14-39-29_5_te9sf5bv.gpx | workouts/1/2022-03-29_14-39-29_5_7dqnr8e6.png | 19a47860994c4f17c4a4b60f894a5d7d
```

So the filenames in the directory and database match.

**Comment by SamR1** [comment]
Thanks for your answer. sorry it still doesn't work :/

Is it still the same error in the logs since the upgrade?
Another check: is it possible to download the gpx file with FitTrackee?

**Comment by escuco** [comment]
Unlike before the last FitTrackee update there are no errors in the log, when displaying the dashboard.

And I'm not able to download the gpx. I'm able to edit or delete the workout, but when I'm clicking the download icon nothing happens.

**Comment by escuco** [comment]
Hello!

During the installation, I've configured the variable as follows:
`export UPLOAD_FOLDER=fittrackee/uploads/`

But the uploads are located to `/fittrackee/uploads/uploads/workouts/1`

-> Just for going sure, the absolute path is: `/home/fittrack/fittrackee//fittrackee/upload/uploads/workouts/1`

Because there are two `fittrackee` subdirectories I've tried different paths for UPLOAD_FOLDER (with restarting the services etc.), but they didn't work either:
`export UPLOAD_FOLDER=fittrackee/fittrackee/uploads/`
`export UPLOAD_FOLDER=fittrackee/fittrackee/uploads/uploads`

So I changed it back and now I'm a little bit confused ;)

**Comment by SamR1** [comment]
Hi,

Sorry, the documentation is not clear :/.
If the `UPLOAD_FOLDER` is not provided, the `uploads` folder created will be:  `<application_directory>/fittrackee/uploads`.

If provided, `UPLOAD_FOLDER` must be initialized with an absolute path. 

For instance, if **FitTrackee** is installed a virtualenv present in `/home/<user>/fittrackee`: 
```
$ pwd
/home/<user>/fittrackee
$ ls -a            
.  ..  .env  .venv
```
the environment variable can be initialized with `/home/<user>/fittrackee` if you want to keep `uploads` folder in the same directory:
```
export UPLOAD_FOLDER=/home/<user>/fittrackee
```
A `uploads` folder will be created after starting the application: 
```
$ pwd
/home/<user>/fittrackee
$ ls -a      
.  ..  .env  fittrackee.log  uploads  .venv
```

I'll update the documentation.
