### ISSUE TITLE
Add German translation

### ISSUE THREAD

**Issue by gorgobacka** [SamR1/FitTrackee#190]
It would be nice, if the German language is supported for this nice project.

Btw: I'm willing to do this. And as far as I understand the code, if might be enough to add a new folder to src/locales/ with translated json files and add the new language in src/utils/locales.ts. Or isn't it?

**Comment by SamR1** [comment]
Hi,

Thanks for your help offer :).

Yes, for the client part. There are also emails in API (this part may need some improvement).

If you want, I can initialize a branch with the needed files and let you do the translations.

**Comment by gorgobacka** [comment]
Thanks for letting me know that there are additional files in the API. I found them now.

You don't need to create a branch. I'm already working on it and I will create a PR, when the changes are ready.

**Comment by SamR1** [comment]
OK, great.  
Feel free to contact me if you have any questions (and there is some info in the [contribution guide](https://github.com/SamR1/FitTrackee/blob/master/CONTRIBUTING.md)).

**Comment by gorgobacka** [comment]
I opened a PR.

**Comment by SamR1** [comment]
Thanks for the PR, I'll take a look.
