### ISSUE TITLE
Layout issue on Workouts page 

### ISSUE THREAD

**Issue by wraezor** [SamR1/FitTrackee#191]
Running FitTrackee v0.6.7

On Firefox 99 (Ubuntu Linux) I get the following on the workout page at default zoom:
![image](https://user-images.githubusercontent.com/7584869/174942707-1157a449-f1c6-4d6b-b220-e3bd811ca3f8.png)

On Google Chrome 101.0.4951.54 (Ubuntu Linux) at least it wraps, but it seems non-ideal to have two lines for this information that's not really informative.
![image](https://user-images.githubusercontent.com/7584869/174942942-860f3655-d331-4e7d-a335-544bbcfd068d.png)

**Comment by SamR1** [comment]
Hi,

Thanks for your feedback.

I'll fix it to at least have the same display than with Chrome (the workout date is displayed correctly in the next column).
