### ISSUE TITLE
ERROR - could not download 6 tiles: 

### ISSUE THREAD

**Issue by PipeItToDevNull** [SamR1/FitTrackee#210]
I have been using the app for several months without issue, suddenly I could not upload any more gpx files. 

I updated to v0.6.9 from 6.1 or 3? I think but the issue persists.

When uploading a GPX I see the following error with several URLs listed. I can load these URLs in a browser and curl them on the host fine `2022/07/12 03:10:13 - fittrackee - ERROR - could not download 6 tiles:`

Note: Uploading old, already loaded GPX files appears to produce the same issue

**Comment by SamR1** [comment]
Hi,

It seems OSM is blocking tiles download (used to generate the static map images), which prevents the workout creation. I'll fix this.

In the meantime, as a workaround, you can enable the default tile server by setting [`DEFAULT_STATICMAP`](https://samr1.github.io/FitTrackee/installation.html#envvar-DEFAULT_STATICMAP) to `true` (the staticmap will be generated with Koomot.de tile server) or set another [tile server](https://wiki.openstreetmap.org/wiki/Tile_servers) that works without subdomains (see [`TILE_SERVER_URL`](https://samr1.github.io/FitTrackee/installation.html#envvar-TILE_SERVER_URL)).

**Comment by PipeItToDevNull** [comment]
Awesome, but apparently I am a monkey. In my `.env` I have 

```
DEFAULT_STATICMAP=true
```

But it tries to download it from 'https://tile.openstreetmap.org/##/###/###.png') still

I may just need to blow up my current data set and load it back in

**Comment by SamR1** [comment]
sorry my bad, the value for `DEFAULT_STATICMAP` should be equal to `True`.  
(I'll fix this to be case insensitive)

**Comment by SamR1** [comment]
I just released a new version with a fix ([v0.6.10](https://github.com/SamR1/FitTrackee/releases/tag/v0.6.10)). It should work with OSM (and `DEFAULT_STATICMAP` to `False`)

**Comment by PipeItToDevNull** [comment]
Brilliant, this indeed fixed the issue without any `.env` changes. 

Thanks!

If you ever add a donate button I will be sure to.

**Comment by escuco** [comment]
Hello!

> If you ever add a donate button I will be sure to.

The same for me, please let us know.

Cheers
Jan
