### ISSUE TITLE
Support alternative database systems

### ISSUE THREAD

**Issue by qwerty287** [SamR1/FitTrackee#227]
Thanks for the nice app! My biggest issue is currently that it only supports PostgreSQL. I'd be very happy if you could add MySQL/MariaDB and SQLite support. Thanks!

**Comment by SamR1** [comment]
Hi,

Unfortunately some upcoming features may rely on PostgreSQL extensions.

May I ask why PostgreSQL is an issue for you? Thank you in advance.
