### ISSUE TITLE
Request: connect to external APIs?

### ISSUE THREAD

**Issue by jat255** [SamR1/FitTrackee#243]
Perhaps this goes against the spirit of a self-hosted tracker, but I still use tools such as Strava and Komoot for their route planning and the fact that my bike computer (Wahoo Element Bolt) will auto-upload tracks to these various commercial services. Some of these external services have fairly fully-featured APIs:

- https://developers.strava.com/docs/reference/
- https://static.komoot.de/doc/external-api/v007/index.html

A nice feature could be to have a UI in the FitTrackee user settings to enter in API credentials for various external services that the app would then poll periodically and auto-import any new tracks it finds. This would require a bit of effort, I'm sure. 

It might be possible to re-use/adapt some of this (MIT licensed) code: https://github.com/flopp/activities

**Comment by SamR1** [comment]
Another problem is that I don't have any accounts on proprietary platforms. It would be difficult to check if the connections are (still) working properly.

For now, workarounds are to develop [3rd-party apps](https://samr1.github.io/FitTrackee/apps.html) to connect FitTrackee to other platforms.

**Comment by jat255** [comment]
That makes sense. I've been working on one over the past week or so (not fully working yet): https://github.com/jat255/strava-to-fittrackee. The bones of it aren't too difficult (although Strava does not provide copies of uploaded GPX files via their API, you have to rebuild it from their "stream API". I'll follow up here when it's done, in case others are interested.

**Comment by jat255** [comment]
Okay, https://github.com/jat255/strava-to-fittrackee is ready for my purposes, and maybe others can use it too if they find a need. I'll go ahead and close this since there's probably not interest in developing such a functionality at this time.
