### ISSUE TITLE
New sport type: "Virtual Ride"

### ISSUE THREAD

**Issue by jat255** [SamR1/FitTrackee#244]
When using a bike trainer and an app like Zwift, these rides get assigned a "virtual" GPX.  For example here was a "ride" I did around London on my trainer:

![image](https://user-images.githubusercontent.com/1278301/197598934-e2f3b18f-de40-40c2-aa64-6321e42d5796.png)

It would be nice to be able to separate these from actual outdoor rides via a different sport type.

**Comment by SamR1** [comment]
released in v0.7.3
