### ISSUE TITLE
How is `workout_date` (and other datetimes) formatted in the API response? 

### ISSUE THREAD

**Issue by jat255** [SamR1/FitTrackee#255]
Sorry if I'm missing something obvious, but I'm trying to reliably parse the string response of the API for `workout_date`, which comes in the format: `Sun, 07 Jul 2019 08:00:00 GMT`.

I cannot see any `strftime` calls in the code that match this format. I see in `models.py` that the column is defined as `db.Column(db.DateTime, index=True, nullable=False)`, and then in the `workouts.py`, the API response is built from `workout.serialize()`, which appears to return the workout_date as-is (`'workout_date': self.workout_date,`). 

Naively, I'd assume that would mean the workout date would come through the API as it is stored in the Postgres database, which I think is more ISO-like (`2020-11-15 21:40:29.709`), but somewhere the day of the week is thrown in there and I can't figure out where.

It looks like I can parse the API response with a `strptime` format of `'%a, %d %b %Y %H:%M:%S GMT'`, but I'm not sure if that's globally true, or if that's a function of settings in my installation, etc., since I can't figure out where in the code this format is coming from. Is it a default somewhere that I'm not seeing?

**Comment by SamR1** [comment]
Hi,

SQLAlchemy returns a [datetime object](https://docs.sqlalchemy.org/en/14/core/type_basics.html#sqlalchemy.types.DateTime) and Flask serializes [datetime into RFC 822 strings](https://flask.palletsprojects.com/en/2.1.x/api/#module-flask.json) in API responses.
