### ISSUE TITLE
UI has white and gray background

### ISSUE THREAD

**Issue by qwerty287** [SamR1/FitTrackee#264]
Hello,
thanks for this nice application. However, there is an UI glitch that results in having both white and gray background (I assume it should be white).

If I look into Firefox' inspection, I can see that the `background-color` is not applied to anything except the `#app` div tag. This affects every single page.

See the screenshot (sorry that it is in German):

![Screenshot 2022-11-06 at 13-48-50 FitTrackee](https://user-images.githubusercontent.com/80460567/200171917-972461dd-7b90-47cc-954f-95ec3449070a.png)

Firefox 106, FitTrackee from latest master, but this issue isn't new.

**Comment by SamR1** [comment]
Hi,

just to be sure to understand the issue, does the screenshot represent the result with 'Save full page' or 'Save visible'?  

for instance with 'Save full page' and **Develop Tools** open (dock to bottom), the footer appears floating in the screenshot:

| screenshot with  **xfce4-screenshooter** | screenshot with **Firefox** (106.0.2 (Linux)) |
|--|--|
| ![Capture d’écran_2022-11-06_19-52-40](https://user-images.githubusercontent.com/3525167/200189550-95ef08ae-6dd1-4a12-8fab-36593efe6a9d.png) | ![Screenshot 2022-11-06 at 19-48-20 FitTrackee](https://user-images.githubusercontent.com/3525167/200189371-0aec6f58-e6a3-45f8-b921-d700caf5596b.png) |

**Comment by SamR1** [comment]
is it possible to have a screenshot with 'Save visible' to see from where the grey background starts?

**Comment by SamR1** [comment]
Thanks for the screenshots.

**Comment by SamR1** [comment]
Hi,

I released a fix. Can you confirm that the background is no longer partially white? Thanks in advance.

**Comment by SamR1** [comment]
great! thanks for the feedback (and for the german translations)
