### ISSUE TITLE
[translations request] Dutch (Nederlands)

### ISSUE THREAD

**Issue by bjornclauw** [SamR1/FitTrackee#270]
Hi @SamR1,

is it possible to add 'dutch' as a new language to weblate?
I can do the entire translation.

Regards

**Comment by SamR1** [comment]
Hi,

yes, no problem to add Dutch, I'll init translation files for Weblate.

**Comment by SamR1** [comment]
Hi,

Ducth is now available on Weblate: https://hosted.weblate.org/languages/nl/fittrackee/

**Comment by SamR1** [comment]
released in v0.7.8, thanks for the entire translation.
