### ISSUE TITLE
[Translation Request] - Italian

### ISSUE THREAD

**Issue by dperruso** [SamR1/FitTrackee#279]
Hi, i would love to translate FitTrackee to Italian.
I already made a request on weblate, and i was waiting for it to be approved, if it's okay with you.

**Comment by SamR1** [comment]
Hi,

No problem to add Italian to FitTrackee, I'll init the files for Weblate.

**Comment by SamR1** [comment]
Hi,

Italian is now available on Weblate: https://hosted.weblate.org/languages/it/fittrackee/.

**Comment by dperruso** [comment]
Hi @SamR1,
i just finished translating everything, and would love to use FitTrackee when it becomes available as a docker image and/or compose.
I will gladly make any necessary changes and corrections to the translation.

**Comment by SamR1** [comment]
Hi,

Thanks for the entire translation, it will be available in the next release.

For now, there is no docker image (see https://github.com/SamR1/FitTrackee/issues/126), but a [docker compose](https://samr1.github.io/FitTrackee/installation.html#docker) file exists for evaluation (and some sample files for custom configuration in this [repository](https://github.com/SamR1/docker-fittrackee)).

**Comment by SamR1** [comment]
released in v0.7.10
