### ISSUE TITLE
Error on uploading gpx file

### ISSUE THREAD

**Issue by vincentxavier** [SamR1/FitTrackee#28]
Uploading gpx file fails with `[Errno 2] No such file or directory: '$HOME/FitTrackee/fittrackee_api/fittrackee_api/uploads/activities/1/tmp/2018-12-21T1743.gpx' -> '$HOME/FitTrackee/fittrackee_api/fittrackee_api/uploads/activities/1/.private/$USER/2018-12-21 16:50:57_Cycling (Transport)_cyimaxnh.gpx'`

If I create `'$HOME/FitTrackee/fittrackee_api/fittrackee_api/uploads/activities/1/.private/$USER/` and move inside the gpx file, it works though !

**Comment by SamR1** [comment]
Hi @vincentxavier 

Thanks for your feedback.
I didn't reproduce this error on a fresh install (on Manjaro Linux), but I thinks the problem is related to temporary file creation with `tempfile.mkstemp()` (whose the return value may depend on OS).

On which OS  is the app running ?
Thanks.

**Comment by vincentxavier** [comment]
Le 26 décembre à 10:33 Sam a écrit
> On which OS  is the app running ?
> Thanks.
On Gentoo GNU/Linux

-- 
Vincent-Xavier JUMEL Id: https://keybase.io/vincentxavier https://blog.thetys-retz.net

Société Libre, Logiciel Libre http://www.april.org/adherer
Parinux, logiciel libre à Paris : http://www.parinux.org

**Comment by SamR1** [comment]
Thanks for your answer.
I'm not familiar with Gentoo, but it seems the path for the `tmp` directory differs.
It should be fixed now (I do not have Gentoo in order to check).

**Comment by SamR1** [comment]
Hi @vincentxavier 
has the fix solved the problem?
thanks

**Comment by vincentxavier** [comment]
Yes, it's fixed !

**Comment by SamR1** [comment]
Thanks for your answer.
