### ISSUE TITLE
Docker Hub not working

### ISSUE THREAD

**Issue by LuposX** [SamR1/FitTrackee#288]
When using the docker hub mentioned in #126 via `docker pull fittrackee/fittrackee`. 
I get the following error:  
`Error response from daemon: manifest for fittrackee/fittrackee:latest not found: manifest unknown: manifest unknown`.

**Comment by chrisf4lc0n** [comment]
At the moment you need to build the docker images locally by following the guide in the documentation.

**Comment by SamR1** [comment]
Hi,

for the moment, only the repository has been created on Docker Hub, but there is no container image yet (see #126).
