### ISSUE TITLE
Could not download [X] tiles

### ISSUE THREAD

**Issue by Thovi98** [SamR1/FitTrackee#313]
As it’s my beginning with FitTrackee, first things first: thanks @SamR1 for this amazing app which is already soo good! I can’t wait for the social features 🤩

As for my issue, it’s the same as https://github.com/SamR1/FitTrackee/issues/210 which was resolved at that time if I understand well.
I’ve set the default maps values:
```
# Workouts
# export TILE_SERVER_URL=
# export STATICMAP_SUBDOMAINS=
# export MAP_ATTRIBUTION=
# export DEFAULT_STATICMAP=False
```

I have a download error in my logs each time I try to upload a workout (here I tried with two different): 
```
2023/03/06 20:45:49 - fittrackee - ERROR - could not download 3 tiles: [(8392, 5497, ''), (8393, 5497, ''), (8394, 5497, '')]
2023/03/06 20:51:08 - fittrackee - ERROR - could not download 4 tiles: [(2118, 1469, ''), (2118, 1470, ''), (2119, 1469, ''), (2119, 1470, '')]
```
Do I have to change the maps values in my .env file, or is it supposed to work "out of the box" with the default values?

***
As a side issue: when an import fails, it doesn’t count as a workout, but it’s still saved on the server. So for my test instance for example, I don’t seem to have any workout saved 
![image](https://user-images.githubusercontent.com/51749973/223218467-3b051355-0a8e-4d5f-80f6-dc9947f1dcf5.png)
But they are
![image](https://user-images.githubusercontent.com/51749973/223218568-d42f077a-aad7-424e-81df-61868dfd78a1.png)
```
ls -lah /home/yunohost.app/fittrackee__2/uploads/workouts/1
total 1.1M
-rw-r--r-- 1 fittrackee__2 fittrackee__2 448K  6 Mar 20:51 2020-01-27_08-37-31_9_CFccd2GWdU8.gpx
-rw-r--r-- 1 fittrackee__2 fittrackee__2 448K  6 Mar 21:00 2020-01-27_08-37-31_9_nyyfN2iKFTY.gpx
-rw-r--r-- 1 fittrackee__2 fittrackee__2  95K  6 Mar 20:45 2023-02-28_12-20-52_5_7pc9oNNDNa0.gpx
-rw-r--r-- 1 fittrackee__2 fittrackee__2  95K  6 Mar 20:43 2023-02-28_12-20-52_5_yWoQwdXDKhw.gpx
```
Is it the normal behaviour that the workouts are still saved although not taken into consideration? As you can see, I’ve duplicates because I’ve tried several times to upload them.

Thanks for all 🤗

**Comment by SamR1** [comment]
Hi @Thovi98 

thanks for the feedback :)

> Do I have to change the maps values in my .env file, or is it supposed to work "out of the box" with the default values?

Yes it should work "out of the box" .  
In this case the default values are:

```
TILE_SERVER_URL=https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
MAP_ATTRIBUTION='&copy; <a href=”http://www.openstreetmap.org/copyright” target=”_blank” rel=”noopener noreferrer”>OpenStreetMap</a> contributors'
DEFAULT_STATICMAP=False
STATICMAP_SUBDOMAINS=''
```

Can you try with another tile server, for instance OSM France?
```
export TILE_SERVER_URL=https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png
export MAP_ATTRIBUTION='fond de carte par <a href="http://www.openstreetmap.fr/mentions-legales/" target="_blank" rel="nofollow noopener">OpenStreetMap France</a>, sous&nbsp;<a href="http://creativecommons.org/licenses/by-sa/2.0/fr/" target="_blank" rel="nofollow noopener">licence CC BY-SA</a>'
export STATICMAP_SUBDOMAINS=a,b,c
```


> Is it the normal behaviour that the workouts are still saved although not taken into consideration? 

The uploaded file should be deleted if the process fails. I will fix this. Thanks for the report.

**Comment by Thovi98** [comment]
> Can you try with another tile server, for instance OSM France?

Yes it works great with those values! Should I make those by default for the Yunohost package?

Thanks for your support!

**Comment by SamR1** [comment]
Great, thanks for your reply.

Just to be sure (and because I'm not familiar Yunohost packaging), is it possible to test by setting the default values in `.env`?

**Comment by Thovi98** [comment]
Yes that's what I had done, but I could try again if you want! I will report here.

**Comment by SamR1** [comment]
No need if you already tried.  
It was just to try to understand why static map generation doesn't work with OSM.org tile server (when FitTrackee is installed with Yunohost package).

**Comment by Thovi98** [comment]
Oh I misunderstoond I think, I've tried only with commenting out the maps values in the .env file, now I will try with the defaults values you pointed out.

```
TILE_SERVER_URL=https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
MAP_ATTRIBUTION='&copy; <a href=”http://www.openstreetmap.org/copyright” target=”_blank” rel=”noopener noreferrer”>OpenStreetMap</a> contributors'
DEFAULT_STATICMAP=False
STATICMAP_SUBDOMAINS=''

```

I will try to report back this afternoon.

**Comment by Thovi98** [comment]
Mmmh interesting, when I set the defaults values, it works great!

So I’ve tried again with commenting out all workouts as initially, and the issue reappeared.

**Comment by Thovi98** [comment]
I’ve just tested a complete new FitTrackee installation with the default values (uncommented, specifically set), and it works great!

**Comment by SamR1** [comment]
Thanks for the feedback.  
It still puzzles me why the values have to be set, but it's great that it now works with the default tile server!

**Comment by SamR1** [comment]
ok, thanks for the feedback.
