### ISSUE TITLE
JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by dpffxhad** [SamR1/FitTrackee#32]
Followed [Wiki](https://github.com/SamR1/FitTrackee/wiki), when I try to login with the credentials provided I get this error `JSON.parse: unexpected character at line 1 column 1 of the JSON data`
From network tab: Post requests are made to `http://localhost:3000/undefined/api/auth/login`

**Comment by SamR1** [comment]
Hi,
it seems the environnement variable **REACT_APP_API_URL** is not initialized.
What is its value in the **Makefile.custom.config** (see [example](https://github.com/SamR1/FitTrackee/blob/master/Makefile.custom.config.example))?

(note: I fixed an error in wiki about config file names)

**Comment by dpffxhad** [comment]
I haven't changed anything in **Makefile.custom.config**

**Comment by SamR1** [comment]
OK, with the default values in **Makefile.config** and **Makefile.custom.config**, the POST requests should be made to `http://localhost:5000/api/auth/login`.  
Do you have the same error with this command?  
```
$ REACT_APP_API_URL=http://localhost:5000 make serve
```

**Comment by dpffxhad** [comment]
That worked, don't know why it doesn't work with default values
