### ISSUE TITLE
[Translation Request] Spanish

### ISSUE THREAD

**Issue by xmgz** [SamR1/FitTrackee#320]
Hi, this is [ghose](https://hosted.weblate.org/user/ghose/) and I could help translating FitTrackee to **spanish** (es) and **galician** (gl)

Please, would you add/activate these languages in *hosted.weblate*? thank you.

**Comment by SamR1** [comment]
Hi

thanks for the issue. 
I opened a separate one for galician.

**Comment by SamR1** [comment]
Hi,

Spanish is available on Weblate: https://hosted.weblate.org/languages/es/fittrackee/

**Comment by xmgz** [comment]
it's done :)
thank you

**Comment by SamR1** [comment]
Thanks! I'll keep the issue open until the release.

**Comment by SamR1** [comment]
released in v0.7.15
