### ISSUE TITLE
[Translation Request] Galician

### ISSUE THREAD

**Issue by SamR1** [SamR1/FitTrackee#323]
see #320

**Comment by SamR1** [comment]
Galician is available on Weblate: https://hosted.weblate.org/languages/gl/fittrackee/

**Comment by xmgz** [comment]
I've finished it. I will try to keep it updated and improved once I use it in production. 

Thank you.

**Comment by SamR1** [comment]
Thank you very much (and sorry for the delay of my reply).

**Comment by SamR1** [comment]
released in v0.7.15
