### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [SamR1/FitTrackee#327]
There are various mentions of AGPL, but "only" or "or later" isn't specified.
https://github.com/SamR1/FitTrackee/search?q=agpl

https://hosted.weblate.org/projects/fittrackee/#information says AGPLv3-only, which makes for an incompatibility that would require negotiating terms with every single translator to fix.
May be that an AGPLv4 comes out in the future, and the consideration is easier to make if it is easy to move over.

**Comment by SamR1** [comment]
Hi,

Sorry for the delay and thanks for pointing this out.  
As "later" was not specified in the repository, I thought it meant "AGPLv3-only". I'll add "only" to avoid any confusion.

I think it must have been another Sam ;), the last time I went to FOSDEM was in 2017.

**Comment by comradekingu** [comment]
Not specifying means "later" isn't granted, but leaves matters open to adding it.
Going specifically with "only" for translations doesn't make sense to me.

The "netwrorking" clause in AGPLv3 is very rudimentary.
It may be that it is improved upon for v4 I would think.
That could also be by necessity, which makes for a lot of people to contact if going with "only".

**Comment by SamR1** [comment]
Ok, thanks for the explanation.

**Comment by SamR1** [comment]
package updated (v0.8.1)
