### ISSUE TITLE
Make "start elevation axis at zero" sticky?

### ISSUE THREAD

**Issue by jat255** [SamR1/FitTrackee#329]
This is a feature request, but it would be really nice if the "start elevation axis at zero" toggle could be saved as a user setting somewhere in the user's profile:

![image](https://user-images.githubusercontent.com/1278301/224610685-1c387a8b-3dec-4862-87a5-7be3f8d15689.png)

Most of my tracks are at a decent elevation due to where I live, so the default of viewing from zero is not super useful, and I find myself unchecking that box quite a bit when inspecting workouts.

This would probably require a database change to add a column to the `users` table, together with a change on the frontend to `IAuthUserProfile` so it can be read as a property in `WorkoutChart/index.vue` rather than defaulting to `true` as it currently does here: https://github.com/SamR1/FitTrackee/blob/master/fittrackee_client/src/components/Workout/WorkoutDetail/WorkoutChart/index.vue#L81

**Comment by SamR1** [comment]
released in v0.7.15
