### ISSUE TITLE
Max speed has incorrect units (seemingly in DB) I think?

### ISSUE THREAD

**Issue by jat255** [SamR1/FitTrackee#335]
I had been wondering about this for a while, because I'd noticed that the "max speed" shown on a Workout page has always been rather off. I figured this had something to do with GPX parsing, but looking more into it, I think the data is getting written into the DB column `max_speed` in imperial units, and then getting "converted" from metric back to imperial on display, resulting in an incorrect number. This seems to also affects records, but seems to only impact rides (and not hikes or walks), as far as I can tell...

Here's some examples from my instance:

| Correct? | Activity type | Max speed of activity on Strava | Max speed shown in FT | `max_speed` for workout in DB |
| -- | ------------ | ---------------------------------- | -------------------------- | -----------------------------------|
| ❌ | Ride | 33.5 mi/h | 19.37 mi/h | 31.17 |
| ❌ | Ride | 29.0 mi/h | 18.7 mi/h | 30.09 |
| ✅ | Hike | 3.78 mi/h | 3.95 mi/h | 6.35 |

First ride from table in FT:

![image](https://user-images.githubusercontent.com/1278301/227252177-6760f6f5-a5d7-444c-b207-db6f95c10c4b.png)

Same in Strava (I loaded the gpx from Strava into FT, so they should be mostly the same, apart from maybe some smoothing):

![image](https://user-images.githubusercontent.com/1278301/227252437-786f4148-5172-401a-bcd6-7f55aa3e65d8.png)

**Comment by SamR1** [comment]
Hi,

The issue seems to be related to extreme values exclusion by `gpxpy`, see https://github.com/SamR1/FitTrackee/issues/48

**Comment by jat255** [comment]
Yes, I think you're right. I'll close this one since I think it's just that max-speed parsing thing messing things up.
