### ISSUE TITLE
Display relevant error message when `<time>` is missing in GPX file

### ISSUE THREAD

**Issue by ptrcnull** [SamR1/FitTrackee#338]
as in the title, `ERROR - 'NoneType' object has no attribute 'tzinfo'` appears in the logs when trying to import a .gpx file; not quite sure how to print the whole stacktrace

**Comment by ptrcnull** [comment]
ah, my gpx file doesn't include a date - just a list of `<trkpt>` elements inside `<trkseg>`

**Comment by SamR1** [comment]
Hi,

**FitTrackee** only supports GPX files with  `<time>`, in order to caculate speeds.
There are some tools allowing to add time infos like gpx.studio.

**Comment by SamR1** [comment]
Yes I'll add it at least in the documentation.

**Comment by ptrcnull** [comment]
thanks, then i guess this issue can be closed ( though seriously, the error message is really cryptic; there should at least be an option to show stacktraces for exceptions )

**Comment by SamR1** [comment]
released in v0.7.15
