### ISSUE TITLE
[Companion Tool] FitTrackee Uploader

### ISSUE THREAD

**Issue by ebrithiljonas** [SamR1/FitTrackee#339]
I made a tool [FitTrackee Uploader](https://github.com/ebrithiljonas/fittrackee-uploader) that allows you to upload your workouts from a specified folder. It supports FIT and GPX files. And it can add some basic statistics to the description. I use it to upload all my Garmin logs from my watch to FitTrackee. 

If you think this could be interesting for other people, maybe link it somewhere here so others can use it too :)

**Comment by xmgz** [comment]
thank you!

I will **try** to use it.

It requires `module "follium"` :(  How do I add it to python?  (python 3.10.10 installed)

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/username/git/fittrackee-uploader/fittrackee-uploader/__main__.py", line 1, in <module>
    import uploader
  File "/home/username/git/fittrackee-uploader/fittrackee-uploader/uploader.py", line 4, in <module>
    import folium
ModuleNotFoundError: No module named 'folium'
```


I'm not educated on this matter, just a trailrunner :D

**Comment by ebrithiljonas** [comment]
Glad to see it worked for someone else, and thanks for the feedback, I will update the Readme to include the dependency step plus your description.

**Comment by ebrithiljonas** [comment]
@xmgz if you want you could open an issue on the projects repo and maybe give a sample file that has no GPS so I could debug and fix it.

**Comment by xmgz** [comment]
sure! later today ;)

**Comment by SamR1** [comment]
thanks!

I added it in the [documentation](https://samr1.github.io/FitTrackee/third_party_tools.html), with [strava-to-fittrackee](https://github.com/jat255/strava-to-fittrackee) tool.

cc @jat255
