### ISSUE TITLE
[Translation Request] Polish

### ISSUE THREAD

**Issue by pigwaa** [SamR1/FitTrackee#351]
Hi.
I will be happy to translate into Polish. How to do it?

**Comment by SamR1** [comment]
Hi,

I have to initialize the translation files so the language can be available in Weblate.
I will update the issue when it's done.

**Comment by SamR1** [comment]
Hi,

Polish is now available on Weblate: https://hosted.weblate.org/languages/pl/fittrackee/.

**Comment by SamR1** [comment]
released in v0.7.18 (translation status: 43%)
