### ISSUE TITLE
Footer overlaps content on user preferences page

### ISSUE THREAD

**Issue by jat255** [SamR1/FitTrackee#359]
Noticed this while working on #358. 

Even when scrolling to the bottom of the user preferences page, the footer will overlap the main content making the buttons only partially visible. Zooming out on the page reveals them. This video shows the issue:

https://github.com/SamR1/FitTrackee/assets/1278301/acf348d2-7f8a-43ef-b1ed-d55873a684a9

I'm not sure the best way to deal with that. Padding the bottom of the content, perhaps?

**Comment by SamR1** [comment]
Hi,

thanks for opening the issue, I'll fix it.

**Comment by SamR1** [comment]
fixed in v0.7.16
