### ISSUE TITLE
Add the functionality to share a training

### ISSUE THREAD

**Issue by escuco** [SamR1/FitTrackee#362]
It would be nice to have a possibility to share a complete training to other people. 

As I can see, the url to an individual training has a cryptical part yet in it, e.g.
https://domain/workouts/**fGcMXYAya8hvye3gCgUsrz**

Maybe one flag to set  a training "public" or "not public" would be enough?

**Comment by SamR1** [comment]
Hi,

I'm currently working on adding social features, with the possibility to define the workout visibility (see issue https://github.com/SamR1/FitTrackee/issues/125).

**Comment by SamR1** [comment]
Hi,

still no donation link, but thanks again for your feedback :)
