### ISSUE TITLE
FitTrackee doesn't build, hits an docker-build Error 17 in step 5

### ISSUE THREAD

**Issue by OliverPifferi** [SamR1/FitTrackee#373]
Hey everyone,

after moving to a new system and building FitTrackee from the scratch again (Debian 12 Bookworm, standard repositories and packages) I encounter an error during stage 5 of the "make docker-build" process regarding the pip-version:

```
 > [fittrackee 5/8] RUN pip install --upgrade pip:                                                                                          
#0 3.596 Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (23.0.1)                                             
#0 3.980 Collecting pip                                                                                                                     
#0 4.173   Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)                                                                                 
#0 4.307      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 16.1 MB/s eta 0:00:00                                                     
#0 4.431 Installing collected packages: pip
#0 4.432   Attempting uninstall: pip
#0 4.434     Found existing installation: pip 23.0.1
#0 4.909     Uninstalling pip-23.0.1:
#0 4.989 ERROR: Could not install packages due to an OSError: [Errno 22] Invalid argument: '/usr/local/lib/python3.10/site-packages/pip-23.0.1.dist-info/'
#0 4.989 
------
failed to solve: process "/bin/sh -c pip install --upgrade pip" did not complete successfully: exit code: 1
make: *** [Makefile:49: docker-build] Error 17
```

I've set up a new system for that, installed all dependencies and am now hitting an error I never encountered before. If I try to upgrade pip manually via "pip install --upgrade pip", the following message appears:

<img width="1405" alt="Bildschirmfoto 2023-06-19 um 08 24 24" src="https://github.com/SamR1/FitTrackee/assets/42076599/6850cf34-8fef-4669-8b26-6b79e2fd3445">

Can anyone help here? Tried the same with a virtual Ubuntu 22.04 and hit the same error so it shouldn't be that Distro-specific.

Thanks in advance,

Oliver

**Comment by OliverPifferi** [comment]
Strange behavior - Docker worked well on the usual bare Metal-system and had its problems on Proxmox as a container template as a base (Debian 12 as well as Ubuntu 22.04). After going with a "real" VM on Proxmox, everything worked as it should - quite odd, but just wanted to let you know that this issue can be closed therefore.

While I have other LXC-containers with Docker enabled working without problems, FitTrackee on Docker has apparently still some issues but in the end.. it worked.

**Comment by SamR1** [comment]
Hi,

Thanks for the feedback, I'll see how to improve the docker files.

**Comment by OliverPifferi** [comment]
> Hi,
> 
> Thanks for the feedback, I'll see how to improve the docker files.

No problem as this seems even more related to FitTrackee and Docker running in a Promox LXC-container while a "real" VM worked as expected. Besides, does the DB-password for Docker also needs to be entered in the db/create.sql-file before making the "build" and "init"-processes? This would be nice to point out in the docs as well.

Anyway, thanks for the feedback and your efforts with this great solution 👍🏻 !

**Comment by OliverPifferi** [comment]
> Maybe the issue is due to FitTrackee installation in the system environment. I'll update the docker files to install it in a virtualenv.
> 
> The docker files in this repo are for evaluation and development purposes. Another [repository](https://github.com/SamR1/docker-fittrackee) exists with sample files for custom configuration (with installation from PyPI and in a virtualenv).

Thanks a lot for this hint with the second repo - this works absolutely fine and eases all my pain or - to be specific - cures it. Everything works fine here (same error on LXC-containers though) and the VPS with Alpine Linux also does its job - just successfully tested it.

THANK YOU!
