### ISSUE TITLE
Inconsistent page with between workout with and without GPS data

### ISSUE THREAD

**Issue by jat255** [SamR1/FitTrackee#384]
This is the minor-est of minor nitpicks, but I noticed this morning that the width of a workout detail page varies if there is GPS data or not, which results in the arrow buttons to navigate back and forth between workouts jumping around (making it annoying to click through more than one activity)

Hopefully this makes the issue clear:

![alignment_issue](https://github.com/SamR1/FitTrackee/assets/1278301/f479044b-14c1-4a95-8cec-0e03631e8b34)

As you can see, the previous/next arrows on these two pages are not aligned.

So far as I can tell, this is due to the added width of the scrollbar for a workout with GPS data, compared to one without. When there's no GPS data, the `.container` div (the parent of `.workout-container`) has a margin of 390 px:

![image](https://github.com/SamR1/FitTrackee/assets/1278301/23ec9ed6-cbdf-437d-abd5-a5fd68591a45)

But when there is GPS data, that same div has margins of 382.5 px:

![image](https://github.com/SamR1/FitTrackee/assets/1278301/c1d9e488-6b68-4421-8c77-da334f635537)

If I add a local CSS rule of

```css
body {
    overflow-y: scroll;
}
```

The buttons stop jumping around, but I'm not sure that's the best solution.

**Comment by SamR1** [comment]
Hi,

Thanks for the bug report.  
This problem occurs on Chrome. There are several solutions:
- display the scrollbar by default to prevent layout change, as you suggest,
- make the clickable area larger, so that despite the layout change, there's no problem clicking on arrow buttons.

**Comment by SamR1** [comment]
example of a fix with both solutions (and custom style on scrollbar) on chrome:

![screenshot](https://github.com/SamR1/FitTrackee/assets/3525167/f6048a83-98a9-4c08-9b93-e2cc8a1ec0bb)

**Comment by jat255** [comment]
Should have mentioned I was on Chrome :) 

Sounds like you found a good fix. Thanks!

**Comment by SamR1** [comment]
thanks for your feedback :)

**Comment by SamR1** [comment]
released in 0.7.19
