### ISSUE TITLE
Add new sport: paragliding

### ISSUE THREAD

**Issue by SamR1** [SamR1/FitTrackee#391]

**Comment by xmgz** [comment]
may I comment? :D 

about new sports... everyone has prefered activities, I'm not saying one is **better** than other, but what's is the criteria to add _paragliding_ and not yoga, swimming, gym session, pilates, meditation, namehereyours,... that, in my opinion, has many more people onboard.

thank you

**Comment by SamR1** [comment]
Hi, 

No problem to comment this issue :)

FitTrackee is built around gpx files with a focus on outdoor activities. It remains very basic, all activities are handled in the same way regardless the sport.
The integration of other kind of sports requires quite a few changes (which are not planned in the roadmap for now).

**Comment by xmgz** [comment]
thank you :+1: 

Given the outdoors nature, please consider to add in the future **open waters swimming**

If you need some .gpx or .fit file from openwater swimming I can send you both so you can check if this kind of activity fits with the database/software requirements.

Thank you


**Note**: I'm currently uploading swimming as "alpine ski" :rofl:  (as I have never went to ski) so I could identify and change that activity type in the future

**Comment by SamR1** [comment]
:D

no problem to add **open waters swimming** :)
Just a question: with no change other than adding a specific icon, it will display elevation and ascent on workout detail. Is this information relevant? or should they simply be renamed in this case?

Can you open an issue to discuss the implementation? thanks :)

**Comment by SamR1** [comment]
released in 0.7.19
