### ISSUE TITLE
PIL.Image module has no attribute ANTIALIAS

### ISSUE THREAD

**Issue by xmgz** [SamR1/FitTrackee#393]
trying to upload a .gpx file (and/or .zip file with several  .gpx files) I got this message in the logs:

`2023/07/14 05:50:56 - fittrackee - ERROR - module 'PIL.Image' has no attribute 'ANTIALIAS'`

Also reported [here](https://github.com/YunoHost-Apps/fittrackee_ynh/issues/26)

thank you

(reported also on Matrix room)

**Comment by SamR1** [comment]
Thanks for the bug report.  
A new version of **Pillow**, which is used by `staticmap`, has been released, and [some constants](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants) have been removed.  

The workaround for now is to pin `pillow` version to 9.5.0 to avoid this issue when installing **FitTrackee** with `pip`.

**Comment by OliverPifferi** [comment]
> Thanks for the bug report. A new version of **Pillow**, which is used by `staticmap`, has been released, and [some constants](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants) have been removed.
> 
> The workaround for now is to pin `pillow` version to 9.5.0 to avoid this issue when installing **FitTrackee** with `pip`.

Will this also affect the repo at https://github.com/SamR1/docker-fittrackee? Just encountered the error here, too - and a "make update migrate" doesn't update the module to the version mentioned.

**Comment by SamR1** [comment]
yes, it also affects this repo. The fix is not released yet (it will be shortly).

**Comment by OliverPifferi** [comment]
> yes, it also affects this repo. The fix is not released yet (it will be shortly).

Great - thanks for the ultra-fast reply!

**Comment by SamR1** [comment]
released in 0.7.19

**Comment by OliverPifferi** [comment]
Works, thank you very much!
