### ISSUE TITLE
[feature] enable dark mode for desktop size

### ISSUE THREAD

**Issue by ballinger** [SamR1/FitTrackee#419]
let the user switch to dark mode for desktop browsers.

**Comment by Thovi98** [comment]
See https://github.com/SamR1/FitTrackee/issues/113

**Comment by ballinger** [comment]
yeah i saw that, but i also see a dark mode when i browse the site on my mobile.. which also would be nice for desktop browsers :)

**Comment by SamR1** [comment]
duplicate of #113
