### ISSUE TITLE
Sharing experiences regarding hosting

### ISSUE THREAD

**Issue by githubtilemaker** [SamR1/FitTrackee#420]
I use a shared hosting contract with hosting.com for a cms. If I see it correctly, I need a separate server for   

Python >= 3.8.1
PostgreSQL 11+

I would be happy to hear how others host their fittrackee instance.

**Comment by githubtilemaker** [comment]
I did this this afternoon following the installation instructions 
https://samr1.github.io/FitTrackee/en/installation.html#id5
and tried it out locally.
I failed miserably. Do you know more detailed instructions?

**Comment by SamR1** [comment]
Hi,

What kind of error did you encounter?

**Comment by githubtilemaker** [comment]
I cloned the repo like explained here: https://samr1.github.io/FitTrackee/en/installation.html#dev-environment


```
$ make install-dev

```
is fine. But 

```
$ make install-db
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"
make: *** [Makefile:164: install-db] Fehler 2

```

**Comment by SamR1** [comment]
Hi,

It seems **FitTrackee** is not installed.   
Can you check whether the virtualenv is correcty initialized?

**Comment by githubtilemaker** [comment]
Thank you for asking and helping me.
I have recreated virtualenv. Now I get this error message.

```
Installing the current project: fittrackee (0.7.22)
(.venv) myuser@myuser-virtual-machine:~/fittrackee/FitTrackee$ make install-db
DROP DATABASE
DROP DATABASE
DROP DATABASE
DROP DATABASE
DROP DATABASE
DROP DATABASE
DROP SCHEMA
DROP ROLE
CREATE ROLE
CREATE SCHEMA
CREATE DATABASE
CREATE DATABASE
CREATE DATABASE
CREATE DATABASE
CREATE DATABASE
CREATE DATABASE
Traceback (most recent call last):
  File "/home/myuser/fittrackee/FitTrackee/.venv/bin/ftcli", line 3, in <module>
    from fittrackee.cli import cli
  File "/home/myuser/fittrackee/FitTrackee/fittrackee/cli/__init__.py", line 3, in <module>
    from fittrackee.migrations.commands import db_cli
  File "/home/myuser/fittrackee/FitTrackee/fittrackee/migrations/commands.py", line 8, in <module>
    from fittrackee.cli.app import app
  File "/home/myuser/fittrackee/FitTrackee/fittrackee/cli/app.py", line 3, in <module>
    app = create_app(init_email=False)
  File "/home/myuser/fittrackee/FitTrackee/fittrackee/__init__.py", line 87, in create_app
    db.init_app(app)
  File "/home/myuser/fittrackee/FitTrackee/.venv/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 310, in init_app
    raise RuntimeError(
RuntimeError: Either 'SQLALCHEMY_DATABASE_URI' or 'SQLALCHEMY_BINDS' must be set.
make: *** [Makefile:165: install-db] Fehler 1

```

**Comment by SamR1** [comment]
OK thanks for your answer.  
It seems the [database URL](https://samr1.github.io/FitTrackee/en/installation.html#envvar-DATABASE_URL) is not set in `.env`.

**Comment by githubtilemaker** [comment]
Thank you for your answer. I really appreciate it. I realise that you don't have to explain things to me that are not part of your software. And here I obviously have gaps. I would like to close this gap. 

You are right. I have treated the` .env` file stepmotherly. Now I'm getting on other step further. I can register. Not at port 3000. But at Port 5000. But I can not login.

I
![1](https://github.com/SamR1/FitTrackee/assets/143515267/63f3c4e6-7e29-43bb-bb97-3fdb4606dd23)


I think there is a problem with the ports? Because the message after `make server` told me, that port 3000 ist the correct one.

![2](https://github.com/SamR1/FitTrackee/assets/143515267/830c362e-692f-4243-8db3-100e346dfbe2)
 can register users. But they are not saved. At least I can't log in with them.

**Comment by githubtilemaker** [comment]
I have now found the solution. I was able to activate the account via

`make user-set-admin USERNAME=<username>`.

I have now found the solution. I was able to activate the account via x.

Yesterday I was confused by the fact that port 3000 did not work.  That's why I didn't even try that further.

Port 5000 works for me.

Now I'm closing the ticket because it's basically running for me now and I first have to familiarise myself theoretically with the environment with Python, which is new to me.

**Comment by SamR1** [comment]
Glad it works :).

If the port 3000 (used for front-end development) doesn't work, an environment variable may be missing.

**Comment by githubtilemaker** [comment]
Would you please give me a hint again?
I am trying the recommended installation `from pypi` https://samr1.github.io/FitTrackee/en/installation.html#from-pypi


`\conninfo` tells me this:

```
fittrackee=# \conninfo
You are connected to database "fittrackee" as user "fittrackee" via socket in "/var/run/postgresql" at port "5432".

```

But if I run `fittrackee` it did not get connection:


```
(venv) myuser@machine:~/FitTrackee$ fittrackee
[2023-09-13 10:01:15 +0200] [6703] [INFO] Starting gunicorn 21.2.0
[2023-09-13 10:01:15 +0200] [6703] [ERROR] Connection in use: ('127.0.0.1', 5432)
[2023-09-13 10:01:15 +0200] [6703] [ERROR] Retrying in 1 second.
[2023-09-13 10:01:16 +0200] [6703] [ERROR] Connection in use: ('127.0.0.1', 5432)
[2023-09-13 10:01:16 +0200] [6703] [ERROR] Retrying in 1 second.
[2023-09-13 10:01:17 +0200] [6703] [ERROR] Connection in use: ('127.0.0.1', 5432)
[2023-09-13 10:01:17 +0200] [6703] [ERROR] Retrying in 1 second.
[2023-09-13 10:01:18 +0200] [6703] [ERROR] Connection in use: ('127.0.0.1', 5432)
[2023-09-13 10:01:18 +0200] [6703] [ERROR] Retrying in 1 second.
[2023-09-13 10:01:19 +0200] [6703] [ERROR] Connection in use: ('127.0.0.1', 5432)
[2023-09-13 10:01:19 +0200] [6703] [ERROR] Retrying in 1 second.
[2023-09-13 10:01:20 +0200] [6703] [ERROR] Can't connect to ('127.0.0.1', 5432)

```

**Comment by githubtilemaker** [comment]
I have managed to put a test instance online. 
Fittrackee supports ActivityPub. Is it possible that I can follow my Fittrackee user from my Mastodon account?

I thought that I could follow the user runner on the fittrackee.example.com instance by searching @runner@fittrackee.example.org. But that doesn't work.

**Comment by githubtilemaker** [comment]
Thank you for your reply.
I misunderstood https://github.com/SamR1/FitTrackee/issues/16
I have now looked more closely. So ActivityPub is planned but not yet realised.


Is it possible to share an activity without a user having to register or log in to my instance?
Specifically, I mean: I upload a GPX file and publish a link to this activity on Mastodon. 
At the moment, another user cannot see this activity if he click on the link. He only sees a login. I have not yet found the possibility to make an activity public.

**Comment by SamR1** [comment]
Hi,

For now, activities cannot be shared, developments are in progress to add this functionality.

**Comment by xmgz** [comment]
as this _issue_ is for **sharing experiences**... mine is using YunoHost on a local device and install **FitTrackee** package.

YNH package mantainer (Tho) tries to help people with issues on our system and updates the package just few days after is released here. Very helpful.

I have using FitTrackee since January, adding every garmin activity and it works nicely for my purpose. Yes, it will be nice when later in development some "sharing" features are added.


I've been checking  used space by this app (about 110 Mb since Jan, single user) with the _gpx_ files. I initially thought it would be much more, so nice :D  (I'm doing some kind of activity almost every day). So disk usage is not an issue, that's what I wanted to share here.

Thank you.
