### ISSUE TITLE
Docker "For Evaluation Purposes"

### ISSUE THREAD

**Issue by iSAT32196** [SamR1/FitTrackee#443]
Hello,

I apologize if this is a bit of a simple question, or not the right place to ask it, but I'm still fairly new with a lot of this stuff. I was able to get FitTrackee installed via Docker, however I see in the install instructions it says "For evaluation purposes, docker files are available, installing FitTrackee from sources." 

I was just wondering what the "For Evaluation purposes" means? Should I not use the docker version as the primary version? Is it just not as up to date as other install methods? Any info you could give would be great, thanks!

**Comment by SamR1** [comment]
Hi,

These Docker files use the development configuration (with an email testing tool) and default passwords, which are not suitable for production environments.

An issue is open about a docker image: https://github.com/SamR1/FitTrackee/issues/126.

**Comment by iSAT32196** [comment]
Ah okay gotcha, thank you! 

Funnily enough, Docker has been the only way I've been able to get FitTrackee working. 

Thank you though for making this program! It's exactly what I've been looking for
