### ISSUE TITLE
Weather API MeteoFrance

### ISSUE THREAD

**Issue by DavidHenryThoreau** [SamR1/FitTrackee#485]
Here's another weather API (no API keys needed) https://github.com/hacf-fr/meteofrance-api  https://github.com/chubin/wttr.in

**Comment by SamR1** [comment]
Hi,

if I'm not mistaken, it's not possible to get historical data (see issue https://github.com/SamR1/FitTrackee/issues/51 for the features used by **FitTrackee**).

Recently, Météo France announced that weather data would be available as open data. Maybe an API will make it easy to get historical data in the future.
