### ISSUE TITLE
Import from CSV

### ISSUE THREAD

**Issue by DavidHenryThoreau** [SamR1/FitTrackee#486]
I've a exported a CSV from tracking app in order to import it to FitTrackee.

Here's some CSV line : 
```
id,uuid,user_id,sport_id,title,gpx,creation_date,modification_date,workout_date,duration,pauses,moving,distance,min_alt,max_alt,descent,ascent,max_speed,ave_speed,bounds,map,map_id,weather_start,weather_end,notes
39,3958a0ec-f780-4579-b7a4-28deffdd8fe5,3,14,Mont Mc,,2018-08-13,,2018-08-13,7:30:00,,7:30:00,20,,3169,,,,,,,,,,-Salomon
```

```
postgres@debian-12:~$ bash -x fittrackee-import-csv.sh
+ psql -c '\c fittrackee' -c 'COPY workouts FROM '\''/var/lib/postgresql/sports.csv'\'' DELIMITER '\'','\'' CSV HEADER'
Vous êtes maintenant connecté à la base de données « fittrackee » en tant qu'utilisateur « postgres ».
COPY 1
```

On the FitTrackee `http://fittrackee//workouts/4N6Ak9JcXMrvop5d4DhCK7` screen I've got (seems well formed) :  
```
durée: 7:30:00
distance: 20 km
```
Nothing on the `http://fittrackee/statistics`

On the `http://fittrackee/workouts/add`, and `Erreur, veuillez réessayer ou contacter l'administrateur.`

**Comment by SamR1** [comment]
Hi,

Some data are missing, preventing from getting statistical data.  

On workout creation, the average and maximum speeds are calculated by the API. These are the missing data.

**Comment by DavidHenryThoreau** [comment]
Thanks for aswer I've insert values that have average and maximum speed.
I'm gonna think about how can I import entries that don't have max and average speed.
Do you have suggestions ?

**Comment by DavidHenryThoreau** [comment]
Thanks for answer I've inserted values that have average and maximum speed, statistics are done :+1: .
I'm gonna think about how can I import entries that don't have max and average speed.
Do you have suggestions ?

**Comment by SamR1** [comment]
One solution is to use the API to add workouts. This way, all the values will be correctly calculated, as the records.

More information in the documentation: 
- https://samr1.github.io/FitTrackee/en/api/workouts.html#post--api-workouts-no_gpx
- https://samr1.github.io/FitTrackee/en/oauth.html

**Comment by DavidHenryThoreau** [comment]
Another question , I've imported 1999 entries but I've `Pas de records.` on the left side.

**Comment by DavidHenryThoreau** [comment]
I'd like to use FitTrackee for sports that don't have distance , avg_speed, max_speed. I mean musculation.
How can I proceed if : distance , avg_speed and max_speed are unavoidable ?

**Comment by SamR1** [comment]
> Another question , I've imported 1999 entries but I've `Pas de records`. on the left side.

Some values are calculated by the API (like average speed, max speed, records), so importing data directly into the database generates incomplete workouts and may lead to errors.
The best way is to use the API to import workouts. 

> I'd like to use FitTrackee for sports that don't have distance , avg_speed, max_speed. I mean musculation.
How can I proceed if : distance , avg_speed and max_speed are unavoid

**FitTrackee** is not designed to handle this type of activity. It is built around gpx files for outdoor activities.  
It's possible to [add a workout without a GPX file](https://samr1.github.io/FitTrackee/en/api/workouts.html#post--api-workouts-no_gpx) as a workaround (for instance when the gps device fails to save the file) and distance is mandatory.

**Comment by DavidHenryThoreau** [comment]
> > Another question , I've imported 1999 entries but I've `Pas de records`. on the left side.
> 
> Some values are calculated by the API (like average speed, max speed, records), so importing data directly into the database generates incomplete workouts and may lead to errors. The best way is to use the API to import workouts.

I don't have found any errors in `fittrackee.log` but I don't know how to import my csv export by using API.
I've read your documentation.

> 
> > I'd like to use FitTrackee for sports that don't have distance , avg_speed, max_speed. I mean musculation.
> > How can I proceed if : distance , avg_speed and max_speed are unavoid
> 
> **FitTrackee** is not designed to handle this type of activity. It is built around gpx files for outdoor activities. It's possible to [add a workout without a GPX file](https://samr1.github.io/FitTrackee/en/api/workouts.html#post--api-workouts-no_gpx) as a workaround (for instance when the gps device fails to save the file) and distance is mandatory.

Yes, I've already import workouts without GPX , which i've done with CSV :+1:  
Strava permits to use activities (Yoga, musculation) which are not outdoor activities only you can see lots of sports https://support.strava.com/hc/en-us/articles/216919407-Supported-Sport-Types-on-Strava 

The `distance` field is not fixed to `not null`

```
fittrackee=# \d workouts
                                              Table « public.workouts »
      Colonne      |            Type             | Collationnement | NULL-able |              Par défaut
-------------------+-----------------------------+-----------------+-----------+--------------------------------------
 id                | integer                     |                 | not null  | nextval('workouts_id_seq'::regclass)
 uuid              | uuid                        |                 | not null  |
 user_id           | integer                     |                 | not null  |
 sport_id          | integer                     |                 | not null  |
 title             | character varying(255)      |                 |           |
 gpx               | character varying(255)      |                 |           |
 creation_date     | timestamp without time zone |                 |           |
 modification_date | timestamp without time zone |                 |           |
 workout_date      | timestamp without time zone |                 | not null  |
 duration          | interval                    |                 | not null  |
 pauses            | interval                    |                 |           |
 moving            | interval                    |                 |           |
 distance          | numeric(6,3)                |                 |           |
 min_alt           | numeric(6,2)                |                 |           |
 max_alt           | numeric(6,2)                |                 |           |
 descent           | numeric(8,3)                |                 |           |
 ascent            | numeric(8,3)                |                 |           |
 max_speed         | numeric(6,2)                |                 |           |
 ave_speed         | numeric(6,2)                |                 |           |
 bounds            | double precision[]          |                 |           |
 map               | character varying(255)      |                 |           |
 map_id            | character varying(50)       |                 |           |
 weather_start     | json                        |                 |           |
 weather_end       | json                        |                 |           |
 notes             | character varying(500)      |                 |           |
Index :
    "workouts_pkey" PRIMARY KEY, btree (id)
    "ix_workouts_map_id" btree (map_id)
    "ix_workouts_sport_id" btree (sport_id)
    "ix_workouts_user_id" btree (user_id)
    "ix_workouts_workout_date" btree (workout_date)
    "workouts_uuid_key" UNIQUE CONSTRAINT, btree (uuid)
Contraintes de clés étrangères :
    "workouts_sport_id_fkey" FOREIGN KEY (sport_id) REFERENCES sports(id)
    "workouts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id)
Référencé par :
    TABLE "records" CONSTRAINT "records_workout_id_fkey" FOREIGN KEY (workout_id) REFERENCES workouts(id)
    TABLE "workout_segments" CONSTRAINT "workout_segments_workout_id_fkey" FOREIGN KEY (workout_id) REFERENCES workouts(id)
```

**Comment by SamR1** [comment]
Yes, some constraints are missing in the database, but are present in the code.
For example, you can't add a workout without the distance with the user interface.

This is why it's recommended to use the API to import workouts. Otherwise, any missing values must be calculated outside the application and also imported into the database. 

There are some examples of tools using **FitTrackee** API endpoints [here](https://samr1.github.io/FitTrackee/en/third_party_tools.html) (example [code](https://github.com/jat255/strava-to-fittrackee/blob/main/strava_to_fittrackee/s2f.py#L887) for importing without GPX file).

**Strava** supports many more sports than **FitTrackee**, which focuses on outdoor activities (since it's mainly built around .gpx files, it offers far fewer features than the other applications).

**Comment by DavidHenryThoreau** [comment]
Thanks for pasting code example, which i've tried to modify :

```
#!/usr/bin/python3

import csv
import datetime

with open("/root/ft/sports_no_head.csv", newline="") as csvfile:
    workouts_reader = csv.reader(csvfile, delimiter=",")
    for index, row in enumerate(workouts_reader):
        duration = datetime.datetime.strptime(row[9], "%H:%M:%S")
        delta = datetime.timedelta(
            hours=duration.hour,
            minutes=duration.minute,
            seconds=duration.second,
        )
        workout_date = f"{row[8]} 00:00"

        # fittrackee_session is an OAuth2Session from requests_oauthlib
        r = fittrackee_session.post(
            f"http://ft.my.tld/api/workouts/no_gpx",
            json=dict(
                distance=row[12],
                duration=delta.total_seconds(),
                notes=row[24],
                sport_id=row[3],
                title=row[4],
                workout_date=workout_date,
            ),
            headers=dict(content_type="application/json"),
        )
        if r.status_code == 201:
            print(f" > row {index} (id: {row[0]}) imported")
        else:
            error_message = r.json().get("message", "unknown")
            print(
                f" > an error has occurred when importing row {index} "
                f"(id: {row[0]}): {error_message} "
                "(checks FitTrackee logs)"
            )
```

```
root@debian-12:~/ft# /usr/bin/python3 import.py
Traceback (most recent call last):
  File "/root/ft/import.py", line 18, in <module>
    r = fittrackee_session.post(
        ^^^^^^^^^^^^^^^^^^
NameError: name 'fittrackee_session' is not defined
```

**Comment by SamR1** [comment]
Hi,

The example is incomplete. The `fittrackee_session` initialisation depends on authentication method (an example is given in the code linked above).

**Comment by DavidHenryThoreau** [comment]
Yes, but I've never use authentication method, I don't understand how to fit with it.

**Comment by SamR1** [comment]
OK. Here's an minimal example adapted from the code linked above: https://codeberg.org/SamR1/csv-importer.
It allows to import a CSV file (after creating an app in **FitTrackee** to get client id and secret).

**Comment by DavidHenryThoreau** [comment]
I'm followed the documentation, I've removed header from CSV I'm getting : 

```
(.venv) root@debian:~/sport/csv-importer# python3 main.py --csv-file ../sports.csv

Please open the following URL to authorize 'CSV importer':

https://ft.my.tld/profile/apps/authorize?response_type=code&client_id=gmdiXXXXXXXXXXXXXn4&scope=workouts%3Awrite&state=n6bnS6XXXXXXXXXXiuO8BXYNl

and enter the URL displayed after application authorization and redirection to get authorization code:
```

```
Autoriser [CSV importer](https://ft.my.tld/profile/apps/3) à utiliser votre compte ?

L'application demande les accès suivants :

workouts:write
    donne les droits en écriture aux routes workouts.
```
I've clicked `Autoriser` but nothing appends.

**Comment by DavidHenryThoreau** [comment]
I've followed the documentation, I've removed header from CSV I'm getting : 

```
(.venv) root@debian:~/sport/csv-importer# python3 main.py --csv-file ../sports.csv

Please open the following URL to authorize 'CSV importer':

https://ft.my.tld/profile/apps/authorize?response_type=code&client_id=gmdiXXXXXXXXXXXXXn4&scope=workouts%3Awrite&state=n6bnS6XXXXXXXXXXiuO8BXYNl

and enter the URL displayed after application authorization and redirection to get authorization code:
```

```
Autoriser [CSV importer](https://ft.my.tld/profile/apps/3) à utiliser votre compte ?

L'application demande les accès suivants :

workouts:write
    donne les droits en écriture aux routes workouts.
```
I've clicked `Autoriser` but nothing appends.

**Comment by SamR1** [comment]
> I've clicked Autoriser but nothing appends.

After clicking on **Autoriser**, you should be redirected to a URL that doesn't exist.
You need to copy this URL, paste it into the terminal and press **Enter** to complete the Authorization flow.

**Comment by SamR1** [comment]
It uses [Requests-OAuthlib](https://requests-oauthlib.readthedocs.io/en/latest/index.html) for OAuth2 (which works through SSL layer).

You can test without HTTPS. To do so, you have to disable checks by setting an environment variable `OAUTHLIB_INSECURE_TRANSPORT`:

```shell
export OAUTHLIB_INSECURE_TRANSPORT=1
```
documentation: https://requests-oauthlib.readthedocs.io/en/latest/examples/real_world_example.html#web-app-example-of-oauth-2-web-application-flow

**Comment by DavidHenryThoreau** [comment]
I've export that variable, enable nginx without https, change .venv, source .venv, export OAUTH variable.
But I'm getting : 

```
Autoriser [CSV importer](http://ft.dmd.zld/profile/apps/4) à utiliser votre compte ?
Erreur. Veuillez réessayer ou contacter l'administrateur.

L'application demande les accès suivants :

workouts:write
    donne les droits en écriture aux routes workouts.
```

I can't enter `Autoriser`

**Comment by SamR1** [comment]
Hi,

I tried with a fresh install with docker (but without nginx) and added `export OAUTHLIB_INSECURE_TRANSPORT=1` in `.env` before sourcing it, the script imported the csv file:

```shell
$ python main.py --csv-file test.csv

Please open the following URL to authorize 'CSV importer':

http://localhost:5000/profile/apps/authorize?response_type=code&client_id=<CLIENT_ID>&scope=workouts%3Awrite&state=6cUDd0xJMCDlTUXnCRcmgsTcoLS6Ah

and enter the URL displayed after application authorization and redirection to get authorization code:
http://localhost/?code=CnL8ieYzMplVW5qqxCSbmXkM7cnjCrnXgIQOzGMmBfnC9G6F&state=6cUDd0xJMCDlTUXnCRcmgsTcoLS6Ah


Starting csv file import...
 > row 0 (id: 39) imported

```

Without `OAUTHLIB_INSECURE_TRANSPORT`, I have the following error
```shell
$ python main.py --csv-file test.csv
[...]
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.

```

**Comment by DavidHenryThoreau** [comment]
I've added `export OAUTHLIB_INSECURE_TRANSPORT=1` before as you've done.

```
(.venv) root@debian:~/sport/csv-importer# echo $OAUTHLIB_INSECURE_TRANSPORT
1
(.venv) root@debian:~/sport/csv-importer#  source .env
(.venv) root@debian:~/sport/csv-importer# python3 main.py --csv-file ../sports.csv

Please open the following URL to authorize 'CSV importer':

http://192.168.122.17:5000/profile/apps/authorize?response_type=code&client_id=5khBLni2IAreBgV2VVZhCHfS&scope=workouts%3Awrite&state=qioq9XuJK6YuvfSJPil3yYKBWc7MBA

and enter the URL displayed after application authorization and redirection to get authorization code:
```

But I stile have :

```
Autoriser [CSV](http://192.168.122.17:5000/profile/apps/1) à utiliser votre compte ?
Erreur. Veuillez réessayer ou contacter l'administrateur.

L'application demande les accès suivants :

workouts:write
    donne les droits en écriture aux routes workouts.
```
In logs : 

```
authlib.oauth2.rfc6749.errors.InsecureTransportError: insecure_transport: OAuth 2 MUST utilize https.
```

I don't understand what differs from your installation ?

**Comment by DavidHenryThoreau** [comment]
I've added `export OAUTHLIB_INSECURE_TRANSPORT=1` before as you've done.

```
(.venv) root@debian:~/sport/csv-importer# echo $OAUTHLIB_INSECURE_TRANSPORT
1
(.venv) root@debian:~/sport/csv-importer#  source .env
(.venv) root@debian:~/sport/csv-importer# python3 main.py --csv-file ../sports.csv

Please open the following URL to authorize 'CSV importer':

http://192.168.122.17:5000/profile/apps/authorize?response_type=code&client_id=5khBLni2IAreBgV2VVZhCHfS&scope=workouts%3Awrite&state=qioq9XuJK6YuvfSJPil3yYKBWc7MBA

and enter the URL displayed after application authorization and redirection to get authorization code:
```

But I still have :

```
Autoriser [CSV](http://192.168.122.17:5000/profile/apps/1) à utiliser votre compte ?
Erreur. Veuillez réessayer ou contacter l'administrateur.

L'application demande les accès suivants :

workouts:write
    donne les droits en écriture aux routes workouts.
```
In logs : 

```
authlib.oauth2.rfc6749.errors.InsecureTransportError: insecure_transport: OAuth 2 MUST utilize https.
```

I don't understand what differs from your installation ?

**Comment by DavidHenryThoreau** [comment]
Is that possible to add in the csv-importer the ability to import equipment ?

**Comment by SamR1** [comment]
If the default equipments are set on FitTrackee, there is no need to change the importer.   The default equipment will be automatically associated with the workout based on the sport.

**Comment by DavidHenryThoreau** [comment]
Right but I'd like to import my csv workouts with right equipment at the same time.

**Comment by SamR1** [comment]
OK, I updated the [script](https://codeberg.org/SamR1/csv-importer/commit/0958da6db5341d4f3dff860b80b409039b19e5f2) to add equipement, with an additional column.

**Comment by DavidHenryThoreau** [comment]
Thanks for adding equipment do you have a csv example ? 
I still have mistakes when importing.

```


Autoriser [CSV](http://192.168.122.17:5000/profile/apps/1) à utiliser votre compte ?
Erreur. Veuillez réessayer ou contacter l'administrateur.

L'application demande les accès suivants :

workouts:write
    donne les droits en écriture aux routes workouts.
```

**Comment by SamR1** [comment]
Hi,

I used the same file as provided in the first comment, but with an additional column containing `equipment_id`  of the equipment to associate.

**Comment by DavidHenryThoreau** [comment]
1/ Ok with real certificate it's ok , no error, thanks 

2/ I've read your documentation : 
Other fields are needs, could you please add all columns in order to get all values during csv import ?

Only few columns are used:

    equipment_id (if empty, no equipment will be associated, even if a default equipment exist for workout sport)
    distance
    duration
    notes
    sport_id
    title
    workout_date

Warning: some data are mandatory, see API documentation.

**Comment by SamR1** [comment]
Hi,

I added [`ascent` and `descent` ](https://codeberg.org/SamR1/csv-importer/commit/b64a23a30f8f768f71fa8bb776da07a97aac0bc1)to match all data handled by the [API endpoint](https://samr1.github.io/FitTrackee/en/api/workouts.html#post--api-workouts-no_gpx).

**Comment by DavidHenryThoreau** [comment]
Hi, thanks a lot :+1: 

I'm trying to import equipment in the csv


I've created a pair of shoes : 
```
 id |                 uuid                 | user_id |                label                 | description | equipment_type_id |       creation_date        | is_active | total_distance | total_duration | total_moving | total_workouts
----+--------------------------------------+---------+--------------------------------------+-------------+-------------------+----------------------------+-----------+----------------+----------------+--------------+----------------
  1 | e6d5f973-e95c-4e71-9fa8-90c5a87bb087 |       1 | Salomon XX             |             |                 1 | 2024-05-16 16:11:37.906669 | t         |          0.000 | 00:00:00       | 00:00:00     | 
```

The csv is formatted like that with equipment I've added the 1 in the end of the line wich is the Salomon XX
```
39,3958a0ec-f780-4579-b7a4-28deffdd8fe5,3,14,Mont Mc,,2018-08-13,,2018-08-13,7:30:00,,7:30:00,20,,3169,,,,,,,,,,Gourde Sac à dos,1
```
I can't import with equipment.
What's I've missed ?

Without equipment it works very well :+1:

**Comment by SamR1** [comment]
Hi,

Glad it works :).

For equipment, the value to add is the short id (string value). You can find it in the equipment detail URL.

**Comment by DavidHenryThoreau** [comment]
Where can i found the string value ? I can't in the SQL query above 
Can you give the SQL query to found ?

**Comment by SamR1** [comment]
Hi,

short id is generated from the equipment uuid (it's not stored in database).

```python
>>> import shortuuid
>>> from uuid import uuid4
>>> equipment_uuid = uuid4()
>>> equipment_uuid
UUID('10812809-d30f-444d-9be4-1470b3e7a0f5')
>>> shortuuid.encode(equipment_uuid)
'4wPhfUXCx9rwHfqrF6CSPR'
```

**Comment by DavidHenryThoreau** [comment]
It's ok I've done some test equipment are well import ! Nice job, thanks a lot !

I've read about you documentation : 
```
Note: for now only one equipment can be associated. 
```
Glad to test it when it will be ready !

Do you plan to let user to add their own equipment ? (I mean : trekking poles, bag and so on)

**Comment by DavidHenryThoreau** [comment]
It's ok I've done some import with equipment all are well import ! Nice job, thanks a lot !

I've read about you documentation : 
```
Note: for now only one equipment can be associated. 
```
Glad to test it when it will be ready !

Do you plan to let user adding their own equipment ? (I mean : trekking poles, bag and so on)

**Comment by DavidHenryThoreau** [comment]
I've read about you documentation : 
```
Note: for now only one equipment can be associated. 
```
Glad to test it when it will be ready !

Do you plan to let user adding their own equipment ? (I mean : trekking poles, bag and so on) 

--
I'm getting this output after importing 1092 workouts : 

```
% source .venv/bin/activate && source .env && python main.py --csv-file ../sports.csv
...
 > row 1069 (id: 679) imported
 > row 1070 (id: 686) imported
 > row 1071 (id: 696) imported
 > row 1072 (id: 699) imported
 > row 1073 (id: 710) imported
 > row 1074 (id: 716) imported
 > row 1075 (id: 721) imported
 > row 1076 (id: 726) imported
 > row 1077 (id: 730) imported
 > row 1078 (id: 735) imported
 > row 1079 (id: 743) imported
 > row 1080 (id: 744) imported
 > row 1081 (id: 745) imported
 > row 1082 (id: 746) imported
 > row 1083 (id: 753) imported
 > row 1084 (id: 756) imported
 > row 1085 (id: 757) imported
 > row 1086 (id: 759) imported
 > row 1087 (id: 760) imported
 > row 1088 (id: 761) imported
 > row 1089 (id: 762) imported
 > row 1090 (id: 767) imported
 > row 1091 (id: 768) imported
 > row 1092 (id: 770) imported
Traceback (most recent call last):
  File "user/csv-importer/.venv/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "user/csv-importer/main.py", line 109, in <module>
    csv_importer.import_csv_file(filepath)
  File "user/csv-importer/main.py", line 89, in import_csv_file
    error_message = r.json().get("message", "unknown")
                    ^^^^^^^^
  File "user/csv-importer/.venv/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by DavidHenryThoreau** [comment]
It's ok, thanks :)
It could be nice to store that value in the equipments table in order to directly get that value ?

**Comment by DavidHenryThoreau** [comment]
I've imported a workout in the database the day and hour are : `2024-05-24 12:42:06.86368` 

```
  id  |                 uuid                 | user_id | sport_id |             title             | gpx |       creation_date       | modification_date |    workout_date     | duration | pauses |  moving  | distance | min_alt | max_alt | descent | ascent  | max_speed | ave_speed | bounds | map | map_id | weather_start | weather_end | notes
------+--------------------------------------+---------+----------+-------------------------------+-----+---------------------------+-------------------+---------------------+----------+--------+----------+----------+---------+---------+---------+---------+-----------+-----------+--------+-----+--------+---------------+-------------+-------
 1334 | a1702a53-5e7a-4f0e-a40d-a82ccd0ce2c1 |       1 |        8 | Pyrenees |     | 2024-05-24 12:42:06.86368 |                   | 2024-05-23 22:00:00 | 01:02:45 |        | 01:02:45 |    7.678 |         |         | 394.930 | 393.330 |      7.34 |      7.34 |        |     |        |               |             |
(1 row)
```

In the fittrackee interface the hour is set to 00:00 : 
```
	Séance	Date	Distance	Durée	Vitesse moy.	Vitesse max	Dénivelé positif	Dénivelé négatif
	Pyrenees 24/05/2024 00:00	7.68 km	1:02:45	7.34 km/h	7.34 km/h	393.33 m	394.93 m
```
In the CSV : 
```
1335,380d2017-3ab9-4470-b770-1c5b19a159ff,3,8,Pyrenees,,2024-05-24,,2024-05-24,01:02:45,,01:02:45,7.678,,,394.93,393.33,11.38,7.41,,,,,,,NXULvEHa69XmnB3Ew7DBjq
```

Why does the hour is different from db to interface ?

**Comment by SamR1** [comment]
Hi,

`2024-05-24 12:42:06.86368` is the `workouts.creation_date` (workout creation date on **FitTrackee**, not displayed on the interface).
The date displayed on the interface is `workouts.workout_date`, which is `2024-05-23 22:00:00` in UTC (24/05/2024 00:00 in **Europe/Paris** timezone).

**Comment by DavidHenryThoreau** [comment]
Thanks for answer.

Is that possible to change the timezone because the records that are done on monday at 00:00 are not count for the right week ?
Also the 22:00 does not seems to bet set on the CSV

**Comment by DavidHenryThoreau** [comment]
Thanks for answer.

I've tried to set timezone in the csv file (the `workouts.workout_date` field) , but it does not :

```
69,158e0484-e75a-4783-a7fd-6ec8d1731f4c,3,1,Alps,,2019-01-11,,2019-01-11 07:00:00,0:30:00,,0:30:00,6,,,0,0,10.8,10.8,,,,,,La Sportiva sac,bPSViQ5RwJotxm23LUXgFZ

```
python main.py --csv-file ../sports.csv
...
Starting csv file import...
 > an error has occurred when importing row 0 (id: 69): Error during workout save. (checks FitTrackee logs)

cat fittrackee.log
2024/05/31 08:38:11 - fittrackee - ERROR - unconverted data remains: :00 00:00
2024/05/31 08:38:11 - werkzeug - INFO - 192.168.1.2 - - [31/May/2024 08:38:11] "POST /api/workouts/no_gpx HTTP/1.1" 500 -
```

**Comment by DavidHenryThoreau** [comment]
Thanks for answer.

I've tried to set timezone in the csv file (the `workouts.workout_date` field) , but it does not :

```
69,158e0484-e75a-4783-a7fd-6ec8d1731f4c,3,1,Alps,,2019-01-11,,2019-01-11 07:00:00,0:30:00,,0:30:00,6,,,0,0,10.8,10.8,,,,,,La Sportiva sac,bPSViQ5RwJotxm23LUXgFZ
```

```
python main.py --csv-file ../sports.csv
...
Starting csv file import...
 > an error has occurred when importing row 0 (id: 69): Error during workout save. (checks FitTrackee logs)

cat fittrackee.log
2024/05/31 08:38:11 - fittrackee - ERROR - unconverted data remains: :00 00:00
2024/05/31 08:38:11 - werkzeug - INFO - 192.168.1.2 - - [31/May/2024 08:38:11] "POST /api/workouts/no_gpx HTTP/1.1" 500 -
```

**Comment by SamR1** [comment]
Hi,

The script has been created for the CSV file provided in the first comment. The workout date has the following format: `%Y-%m-%d`.  
I [updated](https://codeberg.org/SamR1/csv-importer/commit/b937d033b2c49f4aae8eed7716745517e4d943ee) the script to handle the same format as the [API](https://samr1.github.io/FitTrackee/en/api/workouts.html#post--api-workouts-no_gpx): `%Y-%m-%d %H:%M`.

I modified the example to match the expected format for workout date (`2019-01-11 07:00`) and an existing equipment and imported the file:

```csv
69,158e0484-e75a-4783-a7fd-6ec8d1731f4c,3,1,Alps,,2019-01-11,,2019-01-11 07:00,0:30:00,,0:30:00,6,,,0,0,10.8,10.8,,,,,,La Sportiva sac,Dk4ftgGTosMCeeLbhemP2f
```

![image](https://github.com/SamR1/FitTrackee/assets/3525167/54729ce9-b4f6-4e11-b8fb-6660caa0a712)

Values in database:
```sql
fittrackee=# SELECT * FROM workouts;
 id |                 uuid                 | user_id | sport_id | title | gpx |       creation_date        | modification_date |    workout_date     | duration | pauses |  moving  | distance | min_alt | max_alt | descent | ascent | max_speed | ave_speed | bounds | map | map_id | weather_start | weather_end |      notes      
----+--------------------------------------+---------+----------+-------+-----+----------------------------+-------------------+---------------------+----------+--------+----------+----------+---------+---------+---------+--------+-----------+-----------+--------+-----+--------+---------------+-------------+-----------------
  1 | b56260e9-bebc-4df8-a89b-923e73ac6b8a |       1 |        1 | Alps  |     | 2024-06-01 08:52:00.347091 |                   | 2019-01-11 06:00:00 | 00:30:00 |        | 00:30:00 |    6.000 |         |         |   0.000 |  0.000 |     12.00 |     12.00 |        |     |        |               |             | La Sportiva sac
(1 ligne)

fittrackee=# 
```

As the time zone in my case is `Europe/Paris`, the value stored in the database is `2019-01-11 06:00:00`.

Feel free to modify the script to match the CSV file. The script is provided only as an example.

**Comment by DavidHenryThoreau** [comment]
I've used the modified [csv-importer](https://codeberg.org/SamR1/csv-importer) , all is good !
Thanks again :+1:
