### ISSUE TITLE
[Translation Request] EU - Basque 

### ISSUE THREAD

**Issue by erral** [SamR1/FitTrackee#490]
Can you add the Basque language (ISO code EU) in weblate so that we can translate?

Thanks!

**Comment by SamR1** [comment]
Hi,

Basque is now available on Weblate: https://hosted.weblate.org/languages/eu/fittrackee/.

**Comment by erral** [comment]
Thanks!

**Comment by erral** [comment]
I have completed the translation on Weblate :tada:

**Comment by SamR1** [comment]
Great! Thanks, I'll integrate it.

**Comment by SamR1** [comment]
released in v0.7.31
