### ISSUE TITLE
fittrackee installation on debian 12 host

### ISSUE THREAD

**Issue by speefak** [SamR1/FitTrackee#497]
Hello, I've been trying to get Fittrackee up and running for days. I've tried different approaches, such as:

    Compiling Python 3.9 myself.
    Installing Python 3.11 from the sources.
    Installing using pip, pip3.9, pip3.11, and pipx.

I haven't been able to complete the entire manual installation because I don't know where and how to set the environment parameters. Using pipx and the whl installation, I managed to install Fittrackee, but with each reinstall, I encounter the following error when creating the Fittrackee database or during the installation:

 fittrackee
2024/02/18 11:50:50 - fittrackee - WARNING - Redis not available, API rate limits are disabled.
Traceback (most recent call last):
  File "/usr/local/bin/fittrackee", line 5, in <module>
    from fittrackee.__main__ import main
  File "/usr/local/lib/python3.11/dist-packages/fittrackee/__main__.py", line 23, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fittrackee/__init__.py", line 87, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.11/dist-packages/flask_sqlalchemy/extension.py", line 310, in init_app
    raise RuntimeError(
RuntimeError: Either 'SQLALCHEMY_DATABASE_URI' or 'SQLALCHEMY_BINDS' must be set.

Can anyone help me troubleshoot and resolve this issue? I appreciate any assistance!

**Comment by SamR1** [comment]
Hi,

To set environment variables, a `.env` file can be created (an example can be found [here](https://github.com/SamR1/FitTrackee/blob/master/.env.example)). 
Some variables are mandatory, like [`DATABASE_URL`](https://samr1.github.io/FitTrackee/en/installation.html#envvar-DATABASE_URL).

Once the variables have been set, the `.env` file must be sourced to make them available:
```shell
$ source .env
```

**Comment by speefak** [comment]
Thank you for the information. The part about creating the configuration and then loading it via the source command was a bit confusing in the tutorial. I am writing guide to install fittrackee on debian 12 : 

https://speefak.spdns.de/oss_lifestyle/fittrackee-installation-unter-debian-12/

Email , Redis , Worker  Infos comming soon. Now i try to reach the fittrackee installation from other host than local host. Its a little bit tricky, cause i dont know where i can setup these configs. fittrackee does not run on a apache webserver.

**Comment by SamR1** [comment]
Hi,

Thanks for your feedback, I'll try to improve this part.   
The documentation focuses on **FitTrackee**, since the other parts depend on the operating system and host configuration.

**Comment by SamR1** [comment]
documentation updated
