### ISSUE TITLE
GPX File upload max 1MB - How to increase ?

### ISSUE THREAD

**Issue by speefak** [SamR1/FitTrackee#498]
Hi i installed fittrackee and now i want to upload some gpx files. The max file size is set to 1 MB. How can i set 10 MB or 100 MB for filesize uploads ?

Is there any documentation about the configure procedure for fittrackee ? It very different from apache configs ;/ Does fittrackee use the apache2 webserver and PHP ? So must i edit the PHP options and or the webserver options ? 

Install guide => https://speefak.spdns.de/oss_lifestyle/fittrackee-installation-unter-debian-12/

**Comment by SamR1** [comment]
Hi,

In **FitTrackee** [administration](https://samr1.github.io/FitTrackee/en/features.html#application),  you can modify the max size:  

![image](https://github.com/SamR1/FitTrackee/assets/3525167/736c384b-991d-4787-879f-e08b28166ded)

You also need to modify the web server configuration. 
Regarding Apache, I'm sorry, I don't use this web server software. According to some posts, the values to update in Apache config may be `upload_max_filesize` and/or `post_max_size`.

**Comment by speefak** [comment]
Which webserver fittracke uses by default ? I Stopped Apache but fittrackee service is still available.

**Comment by SamR1** [comment]
It uses [gunicorn](https://docs.gunicorn.org/en/stable/index.html) (which can be used with [nginx](https://docs.gunicorn.org/en/stable/deploy.html)).

**Comment by SamR1** [comment]
You need to add admin rights to your account, with **FitTrackee** CLI:

```shell
$ ftcli users update <username> --set-admin true
```

**Comment by speefak** [comment]
![Bildschirmfoto vom 2024-02-21 12-16-30](https://github.com/SamR1/FitTrackee/assets/63617780/fad53efd-2f95-4adb-994d-f39d69d465ef)

Mhh - i did add the accound to the admin group ?!

**Comment by SamR1** [comment]
Ok, you can change the max size in **Application** administration:

![FitTrackee Administration](https://samr1.github.io/FitTrackee/en/_images/fittrackee_screenshot-05.png)
