### ISSUE TITLE
NOTICE - installscript for debian 12 

### ISSUE THREAD

**Issue by speefak** [SamR1/FitTrackee#500]
i am writing an install script for debain 12 and compatible distro like ubuntu. An script is an great example if you dont know what files where you have to edit/create/store and config examples. So i wrote a litte script for fittrackee basic installation 

https://github.com/speefak/fittrackee_installer.sh

**Comment by SamR1** [comment]
Hi,

thanks for the script, I'll add a link in the documentation.

**Comment by SamR1** [comment]
documentation updated
