### ISSUE TITLE
Error on first connection

### ISSUE THREAD

**Issue by dkm** [SamR1/FitTrackee#509]
:wave: 
I'm trying to install fittrackee on a VPS. As a first step, I'm trying to install from sources as I'm going to modify it a bit first.

The `make serve` command looks fine, but then when the first client connects I get:
![image](https://github.com/SamR1/FitTrackee/assets/87603/b94fa397-b712-4ebb-9abc-170383276f4a)

and the server logs:
```
...

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "app_config" does not exist
LINE 2: FROM app_config
             ^

[SQL: SELECT app_config.id AS app_config_id, app_config.max_users AS app_config_max_users, app_config.gpx_limit_import AS app_config_gpx_limit_import, app_config.max_single_file_size AS app_config_max_single_file_size, app_config.max_zip_file_size AS app_config_max_zip_file_size, app_config.admin_contact AS app_config_admin_contact, app_config.privacy_policy_date AS app_config_privacy_policy_date, app_config.privacy_policy AS app_config_privacy_policy, app_config.about AS app_config_about 
FROM app_config]
(Background on this error at: https://sqlalche.me/e/14/f405)
```
I'm not really sure what I'm doing wrong.

**Comment by SamR1** [comment]
Hi,

Are there any errors during database initialization (`make install-db`) ?

**Comment by dkm** [comment]
Ah, that's my issue. I've skipped the `ftcli db upgrade`. Is there an easy way to build `ftcli` from source?

**Comment by SamR1** [comment]
Hi,

do you mean a `make` command that only runs `ftcli db upgrade`?

`make upgrade-db` only runs migrations (`ftcli db upgrade`), while `make install-db` creates the database and run migrations.

Other commands are available in [`MakeFile`](https://github.com/SamR1/FitTrackee/blob/master/Makefile#L288-L299).

Otherwise, the CLI is available after activation of the virtual environment:

```shell
$ source .venv/bin/activate && source .env
$ ftcli --help
Usage: ftcli [OPTIONS] COMMAND [ARGS]...

  FitTrackee Command Line Interface

Options:
  --help  Show this message and exit.

Commands:
  db      Manage database.
  oauth2  Manage OAuth2 tokens.
  users   Manage users.

```

**Comment by dkm** [comment]
Oh, correct. I must have messed up the scripts somehow. Thanks for the help, everything works nicely now :+1:

**Comment by SamR1** [comment]
Great, thanks for the feedback.
