### ISSUE TITLE
Question about suspicious files in the /tmp/ directory within the fittrackee_fittrackee-db container.

### ISSUE THREAD

**Issue by tech1024** [SamR1/FitTrackee#548]
Hello, Can I ask you a question?

![image](https://github.com/SamR1/FitTrackee/assets/160414940/9f75153d-4118-4fbe-926b-41baab88b870)

The `/tmp/` directory contains two suspicious files:

` /tmp/kinsing`

`/tmp/kdevtmpfsi`

I would like to know if this is a mining programme? Is it created when building the image or is my machine implanted with a virus.

**Comment by SamR1** [comment]
Hi,

I build the containers from scratch, these files do not appear:

![Capture d’écran_2024-05-11_15-51-42](https://github.com/SamR1/FitTrackee/assets/3525167/7944fce3-6d7c-404d-96d1-42ed03f14eb7)

FitTrackee database container is based on [PostgreSQL 13 image](https://github.com/SamR1/FitTrackee/blob/master/db/Dockerfile), with a [SQL script](https://github.com/SamR1/FitTrackee/blob/master/db/create.sql) as entrypoint.

**Comment by tech1024** [comment]
Thank you for your reply, I have removed the suspicious files. The problem is not with you. I think it was my own machine that was maliciously implanted with a mining script.
