### ISSUE TITLE
 Failed to find Flask application

### ISSUE THREAD

**Issue by lukasheinz92** [SamR1/FitTrackee#549]
Hello,

when I try to run my containers, I get following error in the `fittrackee` container:

```
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.
Error: Failed to find Flask application or factory in module '__main__'. Use '__main__:name' to specify one.
```

**Comment by SamR1** [comment]
Hi,

what is the value of the environment variable `FLASK_APP` in the `.env` file?

**Comment by lukasheinz92** [comment]
Hi, it is `FLASK_APP=fittrackee/__main__.py`.

**Comment by SamR1** [comment]
Hi,

Thanks for your answer. The value is correct.

Have any changes been made to the configuration?
The container should start up without having to make any changes to the `.env` file after copying it from `.env.docker`.

**Comment by lukasheinz92** [comment]
Hi,

No, I haven't changed any configuration in the `env` file, I only changed the volumes and ports in the docker-compose. Regarding the `.env.docker` file, I haven't copied it to `.env` - the docker-compose contains this:

```
env_file:
  - .env.docker
```

**Comment by SamR1** [comment]
Hi,

can you try with `.env` instead (see [documentation](https://samr1.github.io/FitTrackee/en/installation.html#docker))?  
Some shell scripts source the `.env` file.

**Comment by lukasheinz92** [comment]
Hi,

I followed the documentation:
- `git clone https://github.com/SamR1/FitTrackee.git`
- `cd FitTrackee`
- `cp .env.docker .env`
- `make docker-build`
- I updated the `docker-compose-dev.yml` (the volumes and ports)
- `make docker-init`

But I got this error: `OCI runtime exec failed: exec failed: unable to start container process: exec: "docker/init-database.sh": stat docker/init-database.sh: no such file or directory: unknown
make: *** [Makefile:64: docker-init-db] Error 126` but I can see the `init-database.sh` file in the `docker` subdirectory. In the logs in fittrackee container I can still see the error: `Error: Failed to find Flask application or factory in module '__main__'. Use '__main__:name' to specify one.`

I am trying to run it on Raspberry Pi and I also can see the terminal `...platform (linux/amd64) does not match the detected host platform (linux/arm64/v8)...` - not sure if this can be a problem.

**Comment by SamR1** [comment]
Hi,

does adding the [platform](https://docs.docker.com/compose/compose-file/build/#platforms) in `docker-compose-dev.yml` solve the issue?

**Comment by lukasheinz92** [comment]
Hi,

I tried this:

```
  fittrackee:
    container_name: fittrackee
    platform: "linux/arm64"
    build:
      context: "."
      platforms:
        - "linux/arm64"
```

... but the same issue.

**Comment by SamR1** [comment]
Hi,

Is it the same error?
Python image should exist for `linux/arm64/v8`.

**Comment by lukasheinz92** [comment]
Hi,

yes, it was the same error.

**Comment by SamR1** [comment]
Hi,

`3.10` tag corresponds to `3.10.14-bookworm` . Perhaps another [python image](https://hub.docker.com/_/python) may work. Or additional modifications may also be required in the Docker file.

I'm sorry I can't find an immediate solution, and I don't have a Raspberry Pi available with Raspbian to investigate the issue :/.
I'll try to find one.

**Comment by lukasheinz92** [comment]
I was not able to fix the issue.
