### ISSUE TITLE
Typo: par page instead of per page

### ISSUE THREAD

**Issue by jmlich** [SamR1/FitTrackee#550]
The English string for SELECTS.PER_PAGE.LABEL in fittrackee-client-common, [fittrackee_client/src/locales/cs/common.json](https://github.com/SamR1/FitTrackee/blob/dev/fittrackee_client/src/locales/cs/common.json), string 25
is `par page`, but should be `per page`

**Comment by SamR1** [comment]
Hi,

thanks, I'll fix it.

**Comment by SamR1** [comment]
I let the issue open until the release

**Comment by SamR1** [comment]
released in v0.8.4
