### ISSUE TITLE
[Feature] Improved statistics section with average calculation

### ISSUE THREAD

**Issue by paf38** [SamR1/FitTrackee#566]
Hi,

Do you think it is possible to add, as for the average speed in the statistics section, the calculation of:
* average distance
* average duration
* average ascent
* average descent

The graph could have a select with two options so as not to have too many options:
* sum
* average

I think it could be very useful to see these evolutions over time.

**Comment by SamR1** [comment]
Hi,

I agree, it would be interesting to have this data in the statistics.

**Comment by SamR1** [comment]
released in v0.8.5
