### ISSUE TITLE
Registration doesn't sent account confirmation email

### ISSUE THREAD

**Issue by slackline** [SamR1/FitTrackee#568]
Really keen to give this a whirl, will pair nicely with several years worth of GPX tracks from OpenTracks.

I've got the following `.env` 

```
# Custom variables initialisation
# (can overwrite variables present in Makefile.config)

# Application
# export FLASK_APP=fittrackee
export FLASK_SKIP_DOTENV=1
export HOST=127.0.0.1
export PORT=5000
# export APP_SETTINGS=fittrackee.config.ProductionConfig
export APP_SECRET_KEY='please change me'
# export APP_WORKERS=
export APP_LOG=log/fittrackee.log
export UPLOAD_FOLDER=/home/fittrackee/uploads

# PostgreSQL
export DATABASE_URL=postgresql://fittrackee:fittrackee@localhost:5432/fittrackee
# export DATABASE_DISABLE_POOLING=

# Redis (required for API rate limits and email sending)
# export REDIS_URL=

# API rate limits
# export API_RATE_LIMITS="300 per 5 minutes"

# Emails
export UI_URL=fittrackee.someone.dev
export EMAIL_URL=smtp://someone@gmail.com:#################@smtp.gmail.com:587/?tls=True
export SENDER_EMAIL=someone@gmail.com
# export WORKERS_PROCESSES=

# Workouts
# export TILE_SERVER_URL=
# export STATICMAP_SUBDOMAINS=
# export MAP_ATTRIBUTION=
# export DEFAULT_STATICMAP=False

# Weather
# available weather API providers: darksky, visualcrossing
# export WEATHER_API_PROVIDER=
# export WEATHER_API_KEY=
```

This is configured to be accessible via reverse proxy through Nginx and I've setup the domain the process starts ok manually (not got round to configuring systemd services yet, need to walk before running) and I can access the registration page.

The password is an App Password I generated for Gmail as I use 2FA normally, its all lowercase letter so no quoting/encoding required (I think).

When I register I'm told a registration email has been sent.

![image](https://github.com/SamR1/FitTrackee/assets/776695/bee3b000-4e07-4196-86b3-4f320749675f)

However I never receive an email. I've tried going through the Python code and sprinkling some `print(f"{<var>=}")` in a few places. In `email/email.py` the `EmailService.init_email()` method I placed `print(f"{parsed_url=}")` and can see it gets all the parameters from `email_URL` and splits them ok as `parsed_url` has all the variables noted below.

I also dropped `print(f"{}")` into `email/tasks.py` to show the content of `user` and `email_data` within the `account_confirmation_email()` function but nothing is printed on registering a new account.

```
(fittrackee) [fittrackee@server ~]$ fittrackee 
app.config['EMAIL_URL']='smtp://someone@gmail.com:################@smtp.gmail.com:587/?tls=True'
init_email=True
parsed_url={'host': 'smtp.gmail.com', 'port': 587, 'use_tls': True, 'use_ssl': False, 'username': 'someone@gmail.com', 'password': '#################'}
email_service.__str__=<method-wrapper '__str__' of EmailService object at 0x7efe573cac90>
[2024-06-07 20:55:21 +0200] [873443] [INFO] Starting gunicorn 22.0.0
[2024-06-07 20:55:21 +0200] [873443] [INFO] Listening at: http://127.0.0.1:5000 (873443)
[2024-06-07 20:55:21 +0200] [873443] [INFO] Using worker: sync
[2024-06-07 20:55:21 +0200] [873454] [INFO] Booting worker with pid: 873454
```

I'm thinking there might be a problem with my configuration but am unsure what that might be.

Also how can I start `fittrackee` with a more verbose logging level to get more detailed information reported?

**Comment by SamR1** [comment]
Hi,

no errors appear in the logs (`log/fittrackee.log`)? 

are the task queue workers running without errors?
To run workers with [installation from PyPI](https://samr1.github.io/FitTrackee/en/installation.html#from-pypi), the command is:
```shell
$ flask worker --processes 2
```

For a single-user instance, email sending is not mandatory. You can activate your account and grant admin rights using the [CLI](https://samr1.github.io/FitTrackee/en/cli.html):  
```shell
$ ftcli users update <username> --set-admin true
```

**Comment by slackline** [comment]
Thanks @SamR1 

`log/fittrackee.log` is completely empty, despite multiple restarts and attempts.

I've installed from PyPI but stupidly hadn't paid attention to starting the workers so gave it a whirl after starting `fittrackee` from the `fittrackee` users home directory which didn't work as I was told...

```
(fittrackee) [fittrackee@nshephard ~]$ flask worker --processes 2
Usage: flask worker [OPTIONS] [BROKER_NAME]
Try 'flask worker --help' for help.

Error: Could not locate a Flask application. Use the 'flask --app' option, 'FLASK_APP' environment variable, or a 'wsgi.py' or 'app.py' file in the current directory.
```

However, this is indeed a single user instance (for now at least) and granting admin rights using `ftcli` has done the trick nicely.

Thank you for taking the time to get me back on track, very much appreciated, now to play around uploading some of the 1.4G of `.gpx` files I've accumulated :grinning:

**Comment by SamR1** [comment]
Glad it works :).

For the error with the workers command, it seems that the `.env` file is not sourced.
