### ISSUE TITLE
Configure FitoTrack to use FitTrackee

### ISSUE THREAD

**Issue by DavidHenryThoreau** [SamR1/FitTrackee#572]
I'd like to configure FitoTrack to get records which are saved on FitTrackee.
Configure FitoTrack to save workouts in FitTrackee.

I don't have found documentation here : 
https://samr1.github.io/FitTrackee/fr/search.html?q=fitotrack&check_keywords=yes&area=default

**Comment by SamR1** [comment]
Hi,

**FitoTrack** is just listed as an application, among other alternatives, that can generate gpx files that can be manually added to **FitTrackee**.

**Comment by DavidHenryThoreau** [comment]
In FitoTrack you can `POST` after record a GPX track.

Is that possible to POST to FitTrackee like workout-tracker does ?
https://github.com/jovandeginste/workout-tracker?tab=readme-ov-file#api-usage

**Comment by SamR1** [comment]
Hi,

**FitTrackee**  does not use the API key mechanism, but [OAuth2](https://samr1.github.io/FitTrackee/en/oauth.html) to register client for third-party applications.

**Comment by xmgz** [comment]
hi @DavidHenryThoreau 

related to this issue (`POST` from fitotrack to fittrackee)

have you seen https://codeberg.org/jannis/FitoTrack/issues/498  

**OAuth** is on the works if I understand it correctly. My fitotrack version is 8 months old and this looks like a newer feature oriented to OSM but uses the same mechanism as FitTrackee.

Have you tested a newer version that includes this feature? It would be handy for our fittrackee users **and the fitness/outdoors FOSS ecosystem** have such sinergy, IMO.

thank you


🙏  I posted here as fittrackee user/admin I think it would be nice for our users have this easy method to record their activities, I'm not asking for further support of API-Post method with key, just keeping issue open to post test if eventually FitoTrack implements OAuth2
