### ISSUE TITLE
GPX-Import

### ISSUE THREAD

**Issue by tenni-star** [SamR1/FitTrackee#573]
Hallo, i can not import GPX-Files and Zip-Folder. 

"error, please try again or contact the administrator"

Sorry my English is very bad, i am from German

**Comment by tenni-star** [comment]
Hi 
i send you
[dramatiq.log](https://github.com/user-attachments/files/15859799/dramatiq.log)
[fittrackee.log](https://github.com/user-attachments/files/15859800/fittrackee.log)
[gunicorn.log](https://github.com/user-attachments/files/15859801/gunicorn.log)

it is a new installation, the error is the same  "error, please try again or contact the administrator"

**Comment by SamR1** [comment]
Hi,

it's not related but in the logs there are errors related to Redis (`Error 111 connecting to localhost:6379. Connection refused`). On a single-user instance, it's not mandatory to run workers. A [CLI](https://samr1.github.io/FitTrackee/en/cli.html#users) is available to manage user account.

in the logs, unless I'm mistaken, the error related to a file import is not present. would it be possible to get the logs just after importing a file? thanks in advance.

**Comment by tenni-star** [comment]
Hi,
here are the new logs after importing a file, i see no errors

[fittrackee.log](https://github.com/user-attachments/files/15919555/fittrackee.log)
[gunicorn.log](https://github.com/user-attachments/files/15919558/gunicorn.log)
[dramatiq.log](https://github.com/user-attachments/files/15919559/dramatiq.log)

**Comment by SamR1** [comment]
Hi,

how was the application installed? from sources or from pip?

**Comment by tenni-star** [comment]
Hi, i installed from Production environment. My OS is OpenSuse Tumbleweed . I will try it with Docker

**Comment by SamR1** [comment]
Hi,

To run only the application (since redis is not available), the command is: 
```shell
$ make run-server
```
`make run` starts the application with workers.

Are all mandatory [environment variables](https://github.com/SamR1/FitTrackee/blob/v0.8.5/.env.example) set? especially [`UPLOAD_FOLDER`](https://samr1.github.io/FitTrackee/en/installation.html#envvar-UPLOAD_FOLDER)?

**Comment by tenni-star** [comment]
Hi, the problem is solved, the path to the UPLOAD_FOLDER was not correct, thanks for the quick solution.

LG herbert

**Comment by SamR1** [comment]
Hi,

great, thanks for the feedback.
