### ISSUE TITLE
No maps after update 

### ISSUE THREAD

**Issue by speefak** [SamR1/FitTrackee#594]
Hi after i updated Fittreckee to version 0.8.5 i cant see any maps in the overview and unit view

**Comment by SamR1** [comment]
Hi,

If the application starts but the maps are not displayed, one of the reasons could be that the upload directory is no longer accessible.

Can you check the upload directory?
Have the [environment variables](https://samr1.github.io/FitTrackee/en/installation.html#envvar-UPLOAD_FOLDER) been modified?

**Comment by SamR1** [comment]
Hi @speefak 

Do you still have the issue?

**Comment by speefak** [comment]
no i reinstalled Fitrtrackee from my install script and dont copy the gpx directory. Fittrackee works fine ;)

**Comment by SamR1** [comment]
great!
