### ISSUE TITLE
Figure out workout type from a GPX file

### ISSUE THREAD

**Issue by tadzik** [SamR1/FitTrackee#596]
Workouts exported from FitoTrack (which is one of the recommended apps) include a `<gpx><trk><type>` tag specifying the activity type ("sport" in FitTrackee's lingo). It would be useful (especially when importing zips) if the importer could read that and map it to its Sports, so that the user doesn't have to do that manually (and split their workouts archive into separate zips).

`<type>` is a standard GPX property: https://www.topografix.com/GPX/1/1/#type_trkType

**Comment by SamR1** [comment]
Hi,

Yes I agree, it would be helpful with archives.

**Note**: there is already an issue (#220) for getting sport from <type>. I'll close that one.
