### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by nath67** [SamR1/FitTrackee#597]
Hello,

Are there any plans to link the software to an LDAP directory for centralized authentication?

**Comment by Thovi98** [comment]
There is already an issue tracking this (https://github.com/SamR1/FitTrackee/issues/312) :)

**Comment by SamR1** [comment]
Hi,

thanks @Thovi98.

For now, this is not yet planned in the roadmap.  
I'll close this issue as it is a duplicate.
