### ISSUE TITLE
[translations request] Bulgarian 

### ISSUE THREAD

**Issue by mara21** [SamR1/FitTrackee#608]
Hello,
Please add Bulgarian translation in the Weblate project, I will join (native Bulgarian speaker).

- Marto

**Comment by SamR1** [comment]
Hi,

Bulgarian is now available on Weblate: https://hosted.weblate.org/languages/bg/fittrackee/.

**Comment by mara21** [comment]
Thanks and done, 
waiting for implementation in order to test and fine tune where it is needed.

**Comment by SamR1** [comment]
Hi,

Thanks for the translation, I'll integrate it.

(I'll keep the issue open until the release)

**Comment by SamR1** [comment]
released in v0.8.8
