### ISSUE TITLE
Feature suggestion: Docker images / Docker file

### ISSUE THREAD

**Issue by sgofferj** [SamR1/FitTrackee#61]
I would like to suggest that you provide a docker file or docker images for FitTrackee to simplify deployment and also to make it easier to test and evaluate.

**Comment by SamR1** [comment]
Hi,

Older versions of FitTrackee included docker files.
But after packaging application, I removed them (since I no longer used them in CI and also because I have very basic knowledge of docker).

But I can look to add them for evaluation purposes.

**Comment by sgofferj** [comment]
I wasn't only thinking of evaluation, though. I'd say FitTrackee would be a perfect candidate for containerization and cloud-native running. I'm also not super-familiar with the creation of containers yet - still tinkering - but I do have moved almost everything self-hosted I have into containers. It's so much easier to maintain and administrate.

**Comment by SamR1** [comment]
I understand. Like I said before, my knowledge of docker is basic, especially for production deployment.

That's why I was thinking adding docker files for evaluation at least (I'm working on it right now).

**Comment by sgofferj** [comment]
Great! I'll try then to cook up a working process for automatically creating images.

**Comment by SamR1** [comment]
In addition of docker files for evaluation, I created a repo with sample files to install FitTrackee from pip: https://github.com/SamR1/docker-fittrackee. You can give a try, if you want.  
I prefer not to include them in the main repo for now (since I'm not using docker for deployment, I don't know the best practices).

**Comment by sgofferj** [comment]
OK, I'll have a look! Thanks!
