### ISSUE TITLE
Add a description field to workout

### ISSUE THREAD

**Issue by rhyst** [SamR1/FitTrackee#610]
I'd like to import my Strava activities into Fittrackee. Some of them have descriptions that are longer than 500 characters so some information is lost. Is it possible to remove the 500 character limit on the notes field?

**Comment by SamR1** [comment]
Hi,

I would prefer to keep a limit on the notes field.
Do you have an idea of what length of text might work for you?

**Comment by rhyst** [comment]
I just tested it with Strava and their maximum appears to be about 65,000 characters 😅 

I suspect I don't have anything above 10,000 characters in Strava though so maybe that would be enough? 

Whats the reason for keeping the notes so short?

**Comment by SamR1** [comment]
Hi,

Thank you for your reply.

> Whats the reason for keeping the notes so short?

Originally, it allows to add some additional information (in my case, GPS problems or the bike used (before the release of equipments feature)). 

Note that the [notes will remain private](https://github.com/SamR1/FitTrackee/issues/125) after the release of social features.
It could be interesting to add a description field, longer and with the same visibility as the workout?

**Comment by rhyst** [comment]
A description field like that would be ideal for my use case

**Comment by SamR1** [comment]
released in v0.8.9
