### ISSUE TITLE
[Translation Request] Russian

### ISSUE THREAD

**Issue by sikmir** [SamR1/FitTrackee#629]
Could you please add Russian language in Weblate? I would like to help with translation.

**Comment by SamR1** [comment]
Hi,

Russian is now available on Weblate: https://hosted.weblate.org/languages/ru/fittrackee/.

**Comment by sikmir** [comment]
Thanks!

**Comment by SamR1** [comment]
(I'll keep the issue open until the release 😉)

**Comment by SamR1** [comment]
released in v0.8.10
