### ISSUE TITLE
Only 50 workouts per month shown in calendar

### ISSUE THREAD

**Issue by sgofferj** [SamR1/FitTrackee#64]
Version 0.4.4 - docker

I do at least 2 hikes per day, sometimes more. In January, I e.g. have done 67 hikes. I uploaded them all but only 50 are shown in the calender.

**Comment by sgofferj** [comment]
![Screenshot_20210215_193439](https://user-images.githubusercontent.com/3258466/107978137-f8994700-6fc4-11eb-9524-12d7586c0e58.png)

**Comment by SamR1** [comment]
The calendar should display up to 100 activities, but the api does not return more than 50.

**Comment by SamR1** [comment]
I just released the version 0.4.5 with a fix. Now up to 100 workouts are displayed on calendar.
