### ISSUE TITLE
can not save notes with control characters

### ISSUE THREAD

**Issue by jimbobcraig** [SamR1/FitTrackee#80]
Hello,

I'm not sure if I've pinned down the bug exactly, but I get an error if i put too much text into the Notes box before submitting a new workout/ride. Reducing the number of characters adds the workout without error.

Perhaps (my guess) is that the database field is limited (255?)

Solution: Increase the number of characters in stored notes (I find these handy) Alternativeley limit the data input to the permissable no of characters (ideally with a counter shown (as per sms))

**Comment by SamR1** [comment]
Hi,

Thanks for the bug report.

The database field `notes` is limited to 500 characters as the field in the form (indeed this limitation is not displayed, I will add it). 

Is the content copied and pasted? the error may be related to an invalid character.
(anyway I have to improve security related to inputs).
