### ISSUE TITLE
Display workout with imperial units

### ISSUE THREAD

**Issue by SamR1** [SamR1/FitTrackee#99]
see https://github.com/SamR1/FitTrackee/issues/96#issuecomment-942249950 & https://github.com/SamR1/FitTrackee/issues/18#issuecomment-942881300

**Comment by SamR1** [comment]
https://github.com/SamR1/FitTrackee/issues/18#issuecomment-942881300
> @SamR1 I've submitted one PR already for handling slow movement that I think should not impact the new UI, and I'm now working on the unit conversions. I'll try to make the unit conversion code usable across the new UI by handling most of it in the model itself, but can you make the labels in the new UI, such as "km" and "m" pull from a central variable?

No problem, I will update labels in the new UI.

This feature needs a new user preference (like for the start of week or language), in order to allow user to choose between metric or imperial units. 
On API side, it would be great that depending on this preference, values returned by api are either with metrics units or with imperial units.

**Comment by Fmstrat** [comment]
PR complete: https://github.com/SamR1/FitTrackee/pull/102

**Comment by Fmstrat** [comment]
I should note, I patched this out of a branch with the Docker/React elements so it would be easier to review, but all my testing was done post your React change for Docker.
